/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables;


import com.github.jmart1.example.repo.website.model.Indexes;
import com.github.jmart1.example.repo.website.model.Keys;
import com.github.jmart1.example.repo.website.model.Pacnode;
import com.github.jmart1.example.repo.website.model.tables.records.AccountMasternodeRewardsRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AccountMasternodeRewards extends TableImpl<AccountMasternodeRewardsRecord> {

    /**
     * The reference instance of <code>pacnode.account_masternode_rewards</code>
     */
    public static final AccountMasternodeRewards ACCOUNT_MASTERNODE_REWARDS = new AccountMasternodeRewards();
    private static final long serialVersionUID = 1457105127;
    /**
     * The column <code>pacnode.account_masternode_rewards.account_id</code>.
     */
    public final TableField<AccountMasternodeRewardsRecord, Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>pacnode.account_masternode_rewards.mn_id</code>.
     */
    public final TableField<AccountMasternodeRewardsRecord, Integer> MN_ID = createField("mn_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>pacnode.account_masternode_rewards.reward_amount</code>.
     */
    public final TableField<AccountMasternodeRewardsRecord, Double> REWARD_AMOUNT = createField("reward_amount", org.jooq.impl.SQLDataType.DOUBLE, this, "");
    /**
     * The column <code>pacnode.account_masternode_rewards.fee_amount</code>.
     */
    public final TableField<AccountMasternodeRewardsRecord, Double> FEE_AMOUNT = createField("fee_amount", org.jooq.impl.SQLDataType.DOUBLE, this, "");
    /**
     * The column <code>pacnode.account_masternode_rewards.withdrawal_amount</code>.
     */
    public final TableField<AccountMasternodeRewardsRecord, Double> WITHDRAWAL_AMOUNT = createField("withdrawal_amount", org.jooq.impl.SQLDataType.DOUBLE, this, "");
    /**
     * The column <code>pacnode.account_masternode_rewards.last_payout_date</code>.
     */
    public final TableField<AccountMasternodeRewardsRecord, Timestamp> LAST_PAYOUT_DATE = createField("last_payout_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>pacnode.account_masternode_rewards</code> table reference
     */
    public AccountMasternodeRewards() {
        this(DSL.name("account_masternode_rewards"), null);
    }

    /**
     * Create an aliased <code>pacnode.account_masternode_rewards</code> table reference
     */
    public AccountMasternodeRewards(String alias) {
        this(DSL.name(alias), ACCOUNT_MASTERNODE_REWARDS);
    }

    /**
     * Create an aliased <code>pacnode.account_masternode_rewards</code> table reference
     */
    public AccountMasternodeRewards(Name alias) {
        this(alias, ACCOUNT_MASTERNODE_REWARDS);
    }

    private AccountMasternodeRewards(Name alias, Table<AccountMasternodeRewardsRecord> aliased) {
        this(alias, aliased, null);
    }

    private AccountMasternodeRewards(Name alias, Table<AccountMasternodeRewardsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountMasternodeRewardsRecord> getRecordType() {
        return AccountMasternodeRewardsRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pacnode.PACNODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACCOUNT_MASTERNODE_REWARDS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AccountMasternodeRewardsRecord> getPrimaryKey() {
        return Keys.KEY_ACCOUNT_MASTERNODE_REWARDS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AccountMasternodeRewardsRecord>> getKeys() {
        return Arrays.<UniqueKey<AccountMasternodeRewardsRecord>>asList(Keys.KEY_ACCOUNT_MASTERNODE_REWARDS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountMasternodeRewards as(String alias) {
        return new AccountMasternodeRewards(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountMasternodeRewards as(Name alias) {
        return new AccountMasternodeRewards(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountMasternodeRewards rename(String name) {
        return new AccountMasternodeRewards(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountMasternodeRewards rename(Name name) {
        return new AccountMasternodeRewards(name, null);
    }
}
