/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables;


import com.github.jmart1.example.repo.website.model.Pacnode;
import com.github.jmart1.example.repo.website.model.tables.records.ContactPacnodeRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ContactPacnode extends TableImpl<ContactPacnodeRecord> {

    /**
     * The reference instance of <code>pacnode.contact_pacnode</code>
     */
    public static final ContactPacnode CONTACT_PACNODE = new ContactPacnode();
    private static final long serialVersionUID = -1544084802;
    /**
     * The column <code>pacnode.contact_pacnode.full_name</code>.
     */
    public final TableField<ContactPacnodeRecord, String> FULL_NAME = createField("full_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");
    /**
     * The column <code>pacnode.contact_pacnode.email_address</code>.
     */
    public final TableField<ContactPacnodeRecord, String> EMAIL_ADDRESS = createField("email_address", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");
    /**
     * The column <code>pacnode.contact_pacnode.phone_number</code>.
     */
    public final TableField<ContactPacnodeRecord, String> PHONE_NUMBER = createField("phone_number", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");
    /**
     * The column <code>pacnode.contact_pacnode.twitter_handle</code>.
     */
    public final TableField<ContactPacnodeRecord, String> TWITTER_HANDLE = createField("twitter_handle", org.jooq.impl.SQLDataType.VARCHAR(150), this, "");
    /**
     * The column <code>pacnode.contact_pacnode.message</code>.
     */
    public final TableField<ContactPacnodeRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");
    /**
     * The column <code>pacnode.contact_pacnode.referred_by</code>.
     */
    public final TableField<ContactPacnodeRecord, String> REFERRED_BY = createField("referred_by", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");
    /**
     * The column <code>pacnode.contact_pacnode.insert_date</code>.
     */
    public final TableField<ContactPacnodeRecord, Timestamp> INSERT_DATE = createField("insert_date", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>pacnode.contact_pacnode</code> table reference
     */
    public ContactPacnode() {
        this(DSL.name("contact_pacnode"), null);
    }

    /**
     * Create an aliased <code>pacnode.contact_pacnode</code> table reference
     */
    public ContactPacnode(String alias) {
        this(DSL.name(alias), CONTACT_PACNODE);
    }

    /**
     * Create an aliased <code>pacnode.contact_pacnode</code> table reference
     */
    public ContactPacnode(Name alias) {
        this(alias, CONTACT_PACNODE);
    }

    private ContactPacnode(Name alias, Table<ContactPacnodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private ContactPacnode(Name alias, Table<ContactPacnodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ContactPacnodeRecord> getRecordType() {
        return ContactPacnodeRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pacnode.PACNODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactPacnode as(String alias) {
        return new ContactPacnode(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactPacnode as(Name alias) {
        return new ContactPacnode(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ContactPacnode rename(String name) {
        return new ContactPacnode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ContactPacnode rename(Name name) {
        return new ContactPacnode(name, null);
    }
}
