/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables;


import com.github.jmart1.example.repo.website.model.Indexes;
import com.github.jmart1.example.repo.website.model.Keys;
import com.github.jmart1.example.repo.website.model.Pacnode;
import com.github.jmart1.example.repo.website.model.tables.records.CurrentAccountRewardsRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CurrentAccountRewards extends TableImpl<CurrentAccountRewardsRecord> {

    /**
     * The reference instance of <code>pacnode.current_account_rewards</code>
     */
    public static final CurrentAccountRewards CURRENT_ACCOUNT_REWARDS = new CurrentAccountRewards();
    private static final long serialVersionUID = -1176438881;
    /**
     * The column <code>pacnode.current_account_rewards.account_id</code>.
     */
    public final TableField<CurrentAccountRewardsRecord, Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>pacnode.current_account_rewards.reward_amount</code>.
     */
    public final TableField<CurrentAccountRewardsRecord, Double> REWARD_AMOUNT = createField("reward_amount", org.jooq.impl.SQLDataType.DOUBLE, this, "");
    /**
     * The column <code>pacnode.current_account_rewards.fee_amount</code>.
     */
    public final TableField<CurrentAccountRewardsRecord, Double> FEE_AMOUNT = createField("fee_amount", org.jooq.impl.SQLDataType.DOUBLE, this, "");
    /**
     * The column <code>pacnode.current_account_rewards.withdrawal_amount</code>.
     */
    public final TableField<CurrentAccountRewardsRecord, Double> WITHDRAWAL_AMOUNT = createField("withdrawal_amount", org.jooq.impl.SQLDataType.DOUBLE, this, "");
    /**
     * The column <code>pacnode.current_account_rewards.last_payout_date</code>.
     */
    public final TableField<CurrentAccountRewardsRecord, Timestamp> LAST_PAYOUT_DATE = createField("last_payout_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>pacnode.current_account_rewards</code> table reference
     */
    public CurrentAccountRewards() {
        this(DSL.name("current_account_rewards"), null);
    }

    /**
     * Create an aliased <code>pacnode.current_account_rewards</code> table reference
     */
    public CurrentAccountRewards(String alias) {
        this(DSL.name(alias), CURRENT_ACCOUNT_REWARDS);
    }

    /**
     * Create an aliased <code>pacnode.current_account_rewards</code> table reference
     */
    public CurrentAccountRewards(Name alias) {
        this(alias, CURRENT_ACCOUNT_REWARDS);
    }

    private CurrentAccountRewards(Name alias, Table<CurrentAccountRewardsRecord> aliased) {
        this(alias, aliased, null);
    }

    private CurrentAccountRewards(Name alias, Table<CurrentAccountRewardsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CurrentAccountRewardsRecord> getRecordType() {
        return CurrentAccountRewardsRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pacnode.PACNODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CURRENT_ACCOUNT_REWARDS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CurrentAccountRewardsRecord> getPrimaryKey() {
        return Keys.KEY_CURRENT_ACCOUNT_REWARDS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CurrentAccountRewardsRecord>> getKeys() {
        return Arrays.<UniqueKey<CurrentAccountRewardsRecord>>asList(Keys.KEY_CURRENT_ACCOUNT_REWARDS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CurrentAccountRewards as(String alias) {
        return new CurrentAccountRewards(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CurrentAccountRewards as(Name alias) {
        return new CurrentAccountRewards(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CurrentAccountRewards rename(String name) {
        return new CurrentAccountRewards(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CurrentAccountRewards rename(Name name) {
        return new CurrentAccountRewards(name, null);
    }
}
