/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables;


import com.github.jmart1.example.repo.website.model.Pacnode;
import com.github.jmart1.example.repo.website.model.tables.records.PacnodePayoutsRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.sql.Date;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PacnodePayouts extends TableImpl<PacnodePayoutsRecord> {

    /**
     * The reference instance of <code>pacnode.pacnode_payouts</code>
     */
    public static final PacnodePayouts PACNODE_PAYOUTS = new PacnodePayouts();
    private static final long serialVersionUID = 56548011;
    /**
     * The column <code>pacnode.pacnode_payouts.mn_id</code>.
     */
    public final TableField<PacnodePayoutsRecord, Integer> MN_ID = createField("mn_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>pacnode.pacnode_payouts.pacnode_fees</code>.
     */
    public final TableField<PacnodePayoutsRecord, BigDecimal> PACNODE_FEES = createField("pacnode_fees", org.jooq.impl.SQLDataType.DECIMAL(30, 10), this, "");
    /**
     * The column <code>pacnode.pacnode_payouts.payout_date</code>.
     */
    public final TableField<PacnodePayoutsRecord, Date> PAYOUT_DATE = createField("payout_date", org.jooq.impl.SQLDataType.DATE, this, "");
    /**
     * The column <code>pacnode.pacnode_payouts.net_payout</code>.
     */
    public final TableField<PacnodePayoutsRecord, BigDecimal> NET_PAYOUT = createField("net_payout", org.jooq.impl.SQLDataType.DECIMAL(30, 10), this, "");

    /**
     * Create a <code>pacnode.pacnode_payouts</code> table reference
     */
    public PacnodePayouts() {
        this(DSL.name("pacnode_payouts"), null);
    }

    /**
     * Create an aliased <code>pacnode.pacnode_payouts</code> table reference
     */
    public PacnodePayouts(String alias) {
        this(DSL.name(alias), PACNODE_PAYOUTS);
    }

    /**
     * Create an aliased <code>pacnode.pacnode_payouts</code> table reference
     */
    public PacnodePayouts(Name alias) {
        this(alias, PACNODE_PAYOUTS);
    }

    private PacnodePayouts(Name alias, Table<PacnodePayoutsRecord> aliased) {
        this(alias, aliased, null);
    }

    private PacnodePayouts(Name alias, Table<PacnodePayoutsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PacnodePayoutsRecord> getRecordType() {
        return PacnodePayoutsRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pacnode.PACNODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacnodePayouts as(String alias) {
        return new PacnodePayouts(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacnodePayouts as(Name alias) {
        return new PacnodePayouts(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PacnodePayouts rename(String name) {
        return new PacnodePayouts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PacnodePayouts rename(Name name) {
        return new PacnodePayouts(name, null);
    }
}
