/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables;


import com.github.jmart1.example.repo.website.model.Pacnode;
import com.github.jmart1.example.repo.website.model.tables.records.PacPropVotingHistoryRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PacPropVotingHistory extends TableImpl<PacPropVotingHistoryRecord> {

    /**
     * The reference instance of <code>pacnode.pac_prop_voting_history</code>
     */
    public static final PacPropVotingHistory PAC_PROP_VOTING_HISTORY = new PacPropVotingHistory();
    private static final long serialVersionUID = 1888731409;
    /**
     * The column <code>pacnode.pac_prop_voting_history.dt_datetime</code>.
     */
    public final TableField<PacPropVotingHistoryRecord, Timestamp> DT_DATETIME = createField("dt_datetime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");
    /**
     * The column <code>pacnode.pac_prop_voting_history.account_id</code>.
     */
    public final TableField<PacPropVotingHistoryRecord, Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>pacnode.pac_prop_voting_history.hash</code>.
     */
    public final TableField<PacPropVotingHistoryRecord, String> HASH = createField("hash", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");
    /**
     * The column <code>pacnode.pac_prop_voting_history.yes</code>.
     */
    public final TableField<PacPropVotingHistoryRecord, Byte> YES = createField("yes", org.jooq.impl.SQLDataType.TINYINT, this, "");
    /**
     * The column <code>pacnode.pac_prop_voting_history.no</code>.
     */
    public final TableField<PacPropVotingHistoryRecord, Byte> NO = createField("no", org.jooq.impl.SQLDataType.TINYINT, this, "");
    /**
     * The column <code>pacnode.pac_prop_voting_history.abstain</code>.
     */
    public final TableField<PacPropVotingHistoryRecord, Byte> ABSTAIN = createField("abstain", org.jooq.impl.SQLDataType.TINYINT, this, "");
    /**
     * The column <code>pacnode.pac_prop_voting_history.first_vote_date</code>.
     */
    public final TableField<PacPropVotingHistoryRecord, Timestamp> FIRST_VOTE_DATE = createField("first_vote_date", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>pacnode.pac_prop_voting_history</code> table reference
     */
    public PacPropVotingHistory() {
        this(DSL.name("pac_prop_voting_history"), null);
    }

    /**
     * Create an aliased <code>pacnode.pac_prop_voting_history</code> table reference
     */
    public PacPropVotingHistory(String alias) {
        this(DSL.name(alias), PAC_PROP_VOTING_HISTORY);
    }

    /**
     * Create an aliased <code>pacnode.pac_prop_voting_history</code> table reference
     */
    public PacPropVotingHistory(Name alias) {
        this(alias, PAC_PROP_VOTING_HISTORY);
    }

    private PacPropVotingHistory(Name alias, Table<PacPropVotingHistoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private PacPropVotingHistory(Name alias, Table<PacPropVotingHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PacPropVotingHistoryRecord> getRecordType() {
        return PacPropVotingHistoryRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pacnode.PACNODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacPropVotingHistory as(String alias) {
        return new PacPropVotingHistory(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacPropVotingHistory as(Name alias) {
        return new PacPropVotingHistory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PacPropVotingHistory rename(String name) {
        return new PacPropVotingHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PacPropVotingHistory rename(Name name) {
        return new PacPropVotingHistory(name, null);
    }
}
