/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables;


import com.github.jmart1.example.repo.website.model.Indexes;
import com.github.jmart1.example.repo.website.model.Keys;
import com.github.jmart1.example.repo.website.model.Pacnode;
import com.github.jmart1.example.repo.website.model.tables.records.PacPropVotingRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PacPropVoting extends TableImpl<PacPropVotingRecord> {

    /**
     * The reference instance of <code>pacnode.pac_prop_voting</code>
     */
    public static final PacPropVoting PAC_PROP_VOTING = new PacPropVoting();
    private static final long serialVersionUID = -253832801;
    /**
     * The column <code>pacnode.pac_prop_voting.account_id</code>.
     */
    public final TableField<PacPropVotingRecord, Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>pacnode.pac_prop_voting.hash</code>.
     */
    public final TableField<PacPropVotingRecord, String> HASH = createField("hash", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");
    /**
     * The column <code>pacnode.pac_prop_voting.yes</code>.
     */
    public final TableField<PacPropVotingRecord, Byte> YES = createField("yes", org.jooq.impl.SQLDataType.TINYINT, this, "");
    /**
     * The column <code>pacnode.pac_prop_voting.no</code>.
     */
    public final TableField<PacPropVotingRecord, Byte> NO = createField("no", org.jooq.impl.SQLDataType.TINYINT, this, "");
    /**
     * The column <code>pacnode.pac_prop_voting.abstain</code>.
     */
    public final TableField<PacPropVotingRecord, Byte> ABSTAIN = createField("abstain", org.jooq.impl.SQLDataType.TINYINT, this, "");
    /**
     * The column <code>pacnode.pac_prop_voting.first_vote_date</code>.
     */
    public final TableField<PacPropVotingRecord, Timestamp> FIRST_VOTE_DATE = createField("first_vote_date", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>pacnode.pac_prop_voting</code> table reference
     */
    public PacPropVoting() {
        this(DSL.name("pac_prop_voting"), null);
    }

    /**
     * Create an aliased <code>pacnode.pac_prop_voting</code> table reference
     */
    public PacPropVoting(String alias) {
        this(DSL.name(alias), PAC_PROP_VOTING);
    }

    /**
     * Create an aliased <code>pacnode.pac_prop_voting</code> table reference
     */
    public PacPropVoting(Name alias) {
        this(alias, PAC_PROP_VOTING);
    }

    private PacPropVoting(Name alias, Table<PacPropVotingRecord> aliased) {
        this(alias, aliased, null);
    }

    private PacPropVoting(Name alias, Table<PacPropVotingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PacPropVotingRecord> getRecordType() {
        return PacPropVotingRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pacnode.PACNODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PAC_PROP_VOTING_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PacPropVotingRecord> getPrimaryKey() {
        return Keys.KEY_PAC_PROP_VOTING_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PacPropVotingRecord>> getKeys() {
        return Arrays.<UniqueKey<PacPropVotingRecord>>asList(Keys.KEY_PAC_PROP_VOTING_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacPropVoting as(String alias) {
        return new PacPropVoting(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacPropVoting as(Name alias) {
        return new PacPropVoting(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PacPropVoting rename(String name) {
        return new PacPropVoting(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PacPropVoting rename(Name name) {
        return new PacPropVoting(name, null);
    }
}
