/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables;


import com.github.jmart1.example.repo.website.model.Pacnode;
import com.github.jmart1.example.repo.website.model.tables.records.VPayoutHistoryRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * VIEW
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VPayoutHistory extends TableImpl<VPayoutHistoryRecord> {

    /**
     * The reference instance of <code>pacnode.v_payout_history</code>
     */
    public static final VPayoutHistory V_PAYOUT_HISTORY = new VPayoutHistory();
    private static final long serialVersionUID = 205252964;
    /**
     * The column <code>pacnode.v_payout_history.account_id</code>.
     */
    public final TableField<VPayoutHistoryRecord, Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>pacnode.v_payout_history.mn_id</code>.
     */
    public final TableField<VPayoutHistoryRecord, Integer> MN_ID = createField("mn_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>pacnode.v_payout_history.request_date</code>.
     */
    public final TableField<VPayoutHistoryRecord, Timestamp> REQUEST_DATE = createField("request_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");
    /**
     * The column <code>pacnode.v_payout_history.send_date</code>.
     */
    public final TableField<VPayoutHistoryRecord, Timestamp> SEND_DATE = createField("send_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");
    /**
     * The column <code>pacnode.v_payout_history.reward_payout</code>.
     */
    public final TableField<VPayoutHistoryRecord, Double> REWARD_PAYOUT = createField("reward_payout", org.jooq.impl.SQLDataType.DOUBLE, this, "");
    /**
     * The column <code>pacnode.v_payout_history.fee_amount</code>.
     */
    public final TableField<VPayoutHistoryRecord, Double> FEE_AMOUNT = createField("fee_amount", org.jooq.impl.SQLDataType.DOUBLE, this, "");
    /**
     * The column <code>pacnode.v_payout_history.server_cost_amount</code>.
     */
    public final TableField<VPayoutHistoryRecord, Double> SERVER_COST_AMOUNT = createField("server_cost_amount", org.jooq.impl.SQLDataType.DOUBLE, this, "");
    /**
     * The column <code>pacnode.v_payout_history.payout_address</code>.
     */
    public final TableField<VPayoutHistoryRecord, String> PAYOUT_ADDRESS = createField("payout_address", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");
    /**
     * The column <code>pacnode.v_payout_history.inserted_date</code>.
     */
    public final TableField<VPayoutHistoryRecord, Timestamp> INSERTED_DATE = createField("inserted_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");
    /**
     * The column <code>pacnode.v_payout_history.paid_out</code>.
     */
    public final TableField<VPayoutHistoryRecord, Byte> PAID_OUT = createField("paid_out", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");
    /**
     * The column <code>pacnode.v_payout_history.transaction_id</code>.
     */
    public final TableField<VPayoutHistoryRecord, String> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");
    /**
     * The column <code>pacnode.v_payout_history.confirmations</code>.
     */
    public final TableField<VPayoutHistoryRecord, Long> CONFIRMATIONS = createField("confirmations", org.jooq.impl.SQLDataType.BIGINT, this, "");
    /**
     * The column <code>pacnode.v_payout_history.reinvest</code>.
     */
    public final TableField<VPayoutHistoryRecord, Byte> REINVEST = createField("reinvest", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>pacnode.v_payout_history</code> table reference
     */
    public VPayoutHistory() {
        this(DSL.name("v_payout_history"), null);
    }

    /**
     * Create an aliased <code>pacnode.v_payout_history</code> table reference
     */
    public VPayoutHistory(String alias) {
        this(DSL.name(alias), V_PAYOUT_HISTORY);
    }

    /**
     * Create an aliased <code>pacnode.v_payout_history</code> table reference
     */
    public VPayoutHistory(Name alias) {
        this(alias, V_PAYOUT_HISTORY);
    }

    private VPayoutHistory(Name alias, Table<VPayoutHistoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private VPayoutHistory(Name alias, Table<VPayoutHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VPayoutHistoryRecord> getRecordType() {
        return VPayoutHistoryRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pacnode.PACNODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistory as(String alias) {
        return new VPayoutHistory(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistory as(Name alias) {
        return new VPayoutHistory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VPayoutHistory rename(String name) {
        return new VPayoutHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VPayoutHistory rename(Name name) {
        return new VPayoutHistory(name, null);
    }
}
