/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables;


import com.github.jmart1.example.repo.website.model.Indexes;
import com.github.jmart1.example.repo.website.model.Keys;
import com.github.jmart1.example.repo.website.model.Pacnode;
import com.github.jmart1.example.repo.website.model.tables.records.WithdrawalRequestsRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WithdrawalRequests extends TableImpl<WithdrawalRequestsRecord> {

    /**
     * The reference instance of <code>pacnode.withdrawal_requests</code>
     */
    public static final WithdrawalRequests WITHDRAWAL_REQUESTS = new WithdrawalRequests();
    private static final long serialVersionUID = 1650770300;
    /**
     * The column <code>pacnode.withdrawal_requests.request_id</code>.
     */
    public final TableField<WithdrawalRequestsRecord, Integer> REQUEST_ID = createField("request_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");
    /**
     * The column <code>pacnode.withdrawal_requests.payout_id</code>.
     */
    public final TableField<WithdrawalRequestsRecord, Integer> PAYOUT_ID = createField("payout_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column <code>pacnode.withdrawal_requests.account_id</code>.
     */
    public final TableField<WithdrawalRequestsRecord, Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>pacnode.withdrawal_requests.payout_address</code>.
     */
    public final TableField<WithdrawalRequestsRecord, String> PAYOUT_ADDRESS = createField("payout_address", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");
    /**
     * The column <code>pacnode.withdrawal_requests.status</code>.
     */
    public final TableField<WithdrawalRequestsRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.inline("Pending", org.jooq.impl.SQLDataType.VARCHAR)), this, "");
    /**
     * The column <code>pacnode.withdrawal_requests.confirmations</code>.
     */
    public final TableField<WithdrawalRequestsRecord, Integer> CONFIRMATIONS = createField("confirmations", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");
    /**
     * The column <code>pacnode.withdrawal_requests.withdrawal_amount</code>.
     */
    public final TableField<WithdrawalRequestsRecord, Double> WITHDRAWAL_AMOUNT = createField("withdrawal_amount", org.jooq.impl.SQLDataType.DOUBLE, this, "");
    /**
     * The column <code>pacnode.withdrawal_requests.pacnode_fee</code>.
     */
    public final TableField<WithdrawalRequestsRecord, Double> PACNODE_FEE = createField("pacnode_fee", org.jooq.impl.SQLDataType.DOUBLE, this, "");
    /**
     * The column <code>pacnode.withdrawal_requests.gross_rewards</code>.
     */
    public final TableField<WithdrawalRequestsRecord, Double> GROSS_REWARDS = createField("gross_rewards", org.jooq.impl.SQLDataType.DOUBLE, this, "");
    /**
     * The column <code>pacnode.withdrawal_requests.request_date</code>.
     */
    public final TableField<WithdrawalRequestsRecord, Timestamp> REQUEST_DATE = createField("request_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");
    /**
     * The column <code>pacnode.withdrawal_requests.send_date</code>.
     */
    public final TableField<WithdrawalRequestsRecord, Timestamp> SEND_DATE = createField("send_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");
    /**
     * The column <code>pacnode.withdrawal_requests.transaction_id</code>.
     */
    public final TableField<WithdrawalRequestsRecord, String> TRANSACTION_ID = createField("transaction_id", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>pacnode.withdrawal_requests</code> table reference
     */
    public WithdrawalRequests() {
        this(DSL.name("withdrawal_requests"), null);
    }

    /**
     * Create an aliased <code>pacnode.withdrawal_requests</code> table reference
     */
    public WithdrawalRequests(String alias) {
        this(DSL.name(alias), WITHDRAWAL_REQUESTS);
    }

    /**
     * Create an aliased <code>pacnode.withdrawal_requests</code> table reference
     */
    public WithdrawalRequests(Name alias) {
        this(alias, WITHDRAWAL_REQUESTS);
    }

    private WithdrawalRequests(Name alias, Table<WithdrawalRequestsRecord> aliased) {
        this(alias, aliased, null);
    }

    private WithdrawalRequests(Name alias, Table<WithdrawalRequestsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WithdrawalRequestsRecord> getRecordType() {
        return WithdrawalRequestsRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pacnode.PACNODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.WITHDRAWAL_REQUESTS_ACCOUNT_IDX, Indexes.WITHDRAWAL_REQUESTS_PAYOUT_ADDRESS_IDX, Indexes.WITHDRAWAL_REQUESTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WithdrawalRequestsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_WITHDRAWAL_REQUESTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WithdrawalRequestsRecord> getPrimaryKey() {
        return Keys.KEY_WITHDRAWAL_REQUESTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WithdrawalRequestsRecord>> getKeys() {
        return Arrays.<UniqueKey<WithdrawalRequestsRecord>>asList(Keys.KEY_WITHDRAWAL_REQUESTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequests as(String alias) {
        return new WithdrawalRequests(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequests as(Name alias) {
        return new WithdrawalRequests(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WithdrawalRequests rename(String name) {
        return new WithdrawalRequests(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WithdrawalRequests rename(Name name) {
        return new WithdrawalRequests(name, null);
    }
}
