/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.ContactPacnode;
import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ContactPacnodeRecord extends TableRecordImpl<ContactPacnodeRecord> implements Record7<String, String, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = -1274281440;

    /**
     * Create a detached ContactPacnodeRecord
     */
    public ContactPacnodeRecord() {
        super(ContactPacnode.CONTACT_PACNODE);
    }

    /**
     * Create a detached, initialised ContactPacnodeRecord
     */
    public ContactPacnodeRecord(String fullName, String emailAddress, String phoneNumber, String twitterHandle, String message, String referredBy, Timestamp insertDate) {
        super(ContactPacnode.CONTACT_PACNODE);

        set(0, fullName);
        set(1, emailAddress);
        set(2, phoneNumber);
        set(3, twitterHandle);
        set(4, message);
        set(5, referredBy);
        set(6, insertDate);
    }

    /**
     * Getter for <code>pacnode.contact_pacnode.full_name</code>.
     */
    public String getFullName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pacnode.contact_pacnode.full_name</code>.
     */
    public void setFullName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.contact_pacnode.email_address</code>.
     */
    public String getEmailAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pacnode.contact_pacnode.email_address</code>.
     */
    public void setEmailAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pacnode.contact_pacnode.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pacnode.contact_pacnode.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pacnode.contact_pacnode.twitter_handle</code>.
     */
    public String getTwitterHandle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pacnode.contact_pacnode.twitter_handle</code>.
     */
    public void setTwitterHandle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pacnode.contact_pacnode.message</code>.
     */
    public String getMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pacnode.contact_pacnode.message</code>.
     */
    public void setMessage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pacnode.contact_pacnode.referred_by</code>.
     */
    public String getReferredBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pacnode.contact_pacnode.referred_by</code>.
     */
    public void setReferredBy(String value) {
        set(5, value);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.contact_pacnode.insert_date</code>.
     */
    public Timestamp getInsertDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>pacnode.contact_pacnode.insert_date</code>.
     */
    public void setInsertDate(Timestamp value) {
        set(6, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, String, String, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ContactPacnode.CONTACT_PACNODE.FULL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ContactPacnode.CONTACT_PACNODE.EMAIL_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ContactPacnode.CONTACT_PACNODE.PHONE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ContactPacnode.CONTACT_PACNODE.TWITTER_HANDLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ContactPacnode.CONTACT_PACNODE.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ContactPacnode.CONTACT_PACNODE.REFERRED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return ContactPacnode.CONTACT_PACNODE.INSERT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEmailAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTwitterHandle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getReferredBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getInsertDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEmailAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTwitterHandle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getReferredBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getInsertDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactPacnodeRecord value1(String value) {
        setFullName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactPacnodeRecord value2(String value) {
        setEmailAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactPacnodeRecord value3(String value) {
        setPhoneNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactPacnodeRecord value4(String value) {
        setTwitterHandle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactPacnodeRecord value5(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactPacnodeRecord value6(String value) {
        setReferredBy(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactPacnodeRecord value7(Timestamp value) {
        setInsertDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactPacnodeRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }
}
