/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.CustomerPayouts;
import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CustomerPayoutsRecord extends TableRecordImpl<CustomerPayoutsRecord> implements Record11<Integer, Timestamp, Integer, Double, Double, Double, String, Timestamp, Byte, Byte, Integer> {

    private static final long serialVersionUID = -1130485341;

    /**
     * Create a detached CustomerPayoutsRecord
     */
    public CustomerPayoutsRecord() {
        super(CustomerPayouts.CUSTOMER_PAYOUTS);
    }

    /**
     * Create a detached, initialised CustomerPayoutsRecord
     */
    public CustomerPayoutsRecord(Integer mnId, Timestamp payoutDate, Integer accountId, Double rewardPayout, Double feeAmount, Double serverCostAmount, String payoutAddress, Timestamp insertedDate, Byte paidOut, Byte reinvest, Integer requestId) {
        super(CustomerPayouts.CUSTOMER_PAYOUTS);

        set(0, mnId);
        set(1, payoutDate);
        set(2, accountId);
        set(3, rewardPayout);
        set(4, feeAmount);
        set(5, serverCostAmount);
        set(6, payoutAddress);
        set(7, insertedDate);
        set(8, paidOut);
        set(9, reinvest);
        set(10, requestId);
    }

    /**
     * Getter for <code>pacnode.customer_payouts.mn_id</code>.
     */
    public Integer getMnId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pacnode.customer_payouts.mn_id</code>.
     */
    public void setMnId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.customer_payouts.payout_date</code>.
     */
    public Timestamp getPayoutDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>pacnode.customer_payouts.payout_date</code>.
     */
    public void setPayoutDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>pacnode.customer_payouts.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>pacnode.customer_payouts.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>pacnode.customer_payouts.reward_payout</code>.
     */
    public Double getRewardPayout() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>pacnode.customer_payouts.reward_payout</code>.
     */
    public void setRewardPayout(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>pacnode.customer_payouts.fee_amount</code>.
     */
    public Double getFeeAmount() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>pacnode.customer_payouts.fee_amount</code>.
     */
    public void setFeeAmount(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>pacnode.customer_payouts.server_cost_amount</code>.
     */
    public Double getServerCostAmount() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>pacnode.customer_payouts.server_cost_amount</code>.
     */
    public void setServerCostAmount(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>pacnode.customer_payouts.payout_address</code>.
     */
    public String getPayoutAddress() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pacnode.customer_payouts.payout_address</code>.
     */
    public void setPayoutAddress(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pacnode.customer_payouts.inserted_date</code>.
     */
    public Timestamp getInsertedDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>pacnode.customer_payouts.inserted_date</code>.
     */
    public void setInsertedDate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>pacnode.customer_payouts.paid_out</code>.
     */
    public Byte getPaidOut() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>pacnode.customer_payouts.paid_out</code>.
     */
    public void setPaidOut(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>pacnode.customer_payouts.reinvest</code>.
     */
    public Byte getReinvest() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>pacnode.customer_payouts.reinvest</code>.
     */
    public void setReinvest(Byte value) {
        set(9, value);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.customer_payouts.request_id</code>.
     */
    public Integer getRequestId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>pacnode.customer_payouts.request_id</code>.
     */
    public void setRequestId(Integer value) {
        set(10, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Timestamp, Integer, Double, Double, Double, String, Timestamp, Byte, Byte, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Timestamp, Integer, Double, Double, Double, String, Timestamp, Byte, Byte, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CustomerPayouts.CUSTOMER_PAYOUTS.MN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return CustomerPayouts.CUSTOMER_PAYOUTS.PAYOUT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CustomerPayouts.CUSTOMER_PAYOUTS.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return CustomerPayouts.CUSTOMER_PAYOUTS.REWARD_PAYOUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return CustomerPayouts.CUSTOMER_PAYOUTS.FEE_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return CustomerPayouts.CUSTOMER_PAYOUTS.SERVER_COST_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CustomerPayouts.CUSTOMER_PAYOUTS.PAYOUT_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return CustomerPayouts.CUSTOMER_PAYOUTS.INSERTED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return CustomerPayouts.CUSTOMER_PAYOUTS.PAID_OUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return CustomerPayouts.CUSTOMER_PAYOUTS.REINVEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return CustomerPayouts.CUSTOMER_PAYOUTS.REQUEST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getPayoutDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getRewardPayout();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getFeeAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getServerCostAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPayoutAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getInsertedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getPaidOut();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component10() {
        return getReinvest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getRequestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getPayoutDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getRewardPayout();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getFeeAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getServerCostAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPayoutAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getInsertedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getPaidOut();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getReinvest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getRequestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerPayoutsRecord value1(Integer value) {
        setMnId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerPayoutsRecord value2(Timestamp value) {
        setPayoutDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerPayoutsRecord value3(Integer value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerPayoutsRecord value4(Double value) {
        setRewardPayout(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerPayoutsRecord value5(Double value) {
        setFeeAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerPayoutsRecord value6(Double value) {
        setServerCostAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerPayoutsRecord value7(String value) {
        setPayoutAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerPayoutsRecord value8(Timestamp value) {
        setInsertedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerPayoutsRecord value9(Byte value) {
        setPaidOut(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerPayoutsRecord value10(Byte value) {
        setReinvest(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerPayoutsRecord value11(Integer value) {
        setRequestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerPayoutsRecord values(Integer value1, Timestamp value2, Integer value3, Double value4, Double value5, Double value6, String value7, Timestamp value8, Byte value9, Byte value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }
}
