/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.CustomerMasternodeMapping;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CustomerMasternodeMappingRecord extends UpdatableRecordImpl<CustomerMasternodeMappingRecord> implements Record3<String, Integer, BigDecimal> {

    private static final long serialVersionUID = -873520070;

    /**
     * Create a detached CustomerMasternodeMappingRecord
     */
    public CustomerMasternodeMappingRecord() {
        super(CustomerMasternodeMapping.CUSTOMER_MASTERNODE_MAPPING);
    }

    /**
     * Create a detached, initialised CustomerMasternodeMappingRecord
     */
    public CustomerMasternodeMappingRecord(String accountId, Integer mnId, BigDecimal investedAmount) {
        super(CustomerMasternodeMapping.CUSTOMER_MASTERNODE_MAPPING);

        set(0, accountId);
        set(1, mnId);
        set(2, investedAmount);
    }

    /**
     * Getter for <code>pacnode.customer_masternode_mapping.account_id</code>.
     */
    public String getAccountId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pacnode.customer_masternode_mapping.account_id</code>.
     */
    public void setAccountId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.customer_masternode_mapping.mn_id</code>.
     */
    public Integer getMnId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>pacnode.customer_masternode_mapping.mn_id</code>.
     */
    public void setMnId(Integer value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.customer_masternode_mapping.invested_amount</code>.
     */
    public BigDecimal getInvestedAmount() {
        return (BigDecimal) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>pacnode.customer_masternode_mapping.invested_amount</code>.
     */
    public void setInvestedAmount(BigDecimal value) {
        set(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, BigDecimal> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, BigDecimal> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CustomerMasternodeMapping.CUSTOMER_MASTERNODE_MAPPING.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CustomerMasternodeMapping.CUSTOMER_MASTERNODE_MAPPING.MN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return CustomerMasternodeMapping.CUSTOMER_MASTERNODE_MAPPING.INVESTED_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getMnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getInvestedAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getMnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getInvestedAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerMasternodeMappingRecord value1(String value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerMasternodeMappingRecord value2(Integer value) {
        setMnId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerMasternodeMappingRecord value3(BigDecimal value) {
        setInvestedAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerMasternodeMappingRecord values(String value1, Integer value2, BigDecimal value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
