/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.CustomerAccount;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CustomerAccountRecord extends UpdatableRecordImpl<CustomerAccountRecord> implements Record9<Integer, String, String, String, Integer, Integer, String, String, Byte> {

    private static final long serialVersionUID = 18749533;

    /**
     * Create a detached CustomerAccountRecord
     */
    public CustomerAccountRecord() {
        super(CustomerAccount.CUSTOMER_ACCOUNT);
    }

    /**
     * Create a detached, initialised CustomerAccountRecord
     */
    public CustomerAccountRecord(Integer uuid, String accountId, String username, String referredBy, Integer originalInvestment, Integer totalPaidOut, String payoutAddress, String investAddress, Byte withdrawed) {
        super(CustomerAccount.CUSTOMER_ACCOUNT);

        set(0, uuid);
        set(1, accountId);
        set(2, username);
        set(3, referredBy);
        set(4, originalInvestment);
        set(5, totalPaidOut);
        set(6, payoutAddress);
        set(7, investAddress);
        set(8, withdrawed);
    }

    /**
     * Getter for <code>pacnode.customer_account.uuid</code>.
     */
    public Integer getUuid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pacnode.customer_account.uuid</code>.
     */
    public void setUuid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.customer_account.account_id</code>.
     */
    public String getAccountId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pacnode.customer_account.account_id</code>.
     */
    public void setAccountId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pacnode.customer_account.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pacnode.customer_account.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pacnode.customer_account.referred_by</code>.
     */
    public String getReferredBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pacnode.customer_account.referred_by</code>.
     */
    public void setReferredBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pacnode.customer_account.original_investment</code>.
     */
    public Integer getOriginalInvestment() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>pacnode.customer_account.original_investment</code>.
     */
    public void setOriginalInvestment(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>pacnode.customer_account.total_paid_out</code>.
     */
    public Integer getTotalPaidOut() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>pacnode.customer_account.total_paid_out</code>.
     */
    public void setTotalPaidOut(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>pacnode.customer_account.payout_address</code>.
     */
    public String getPayoutAddress() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pacnode.customer_account.payout_address</code>.
     */
    public void setPayoutAddress(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pacnode.customer_account.invest_address</code>.
     */
    public String getInvestAddress() {
        return (String) get(7);
    }

    /**
     * Setter for <code>pacnode.customer_account.invest_address</code>.
     */
    public void setInvestAddress(String value) {
        set(7, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.customer_account.withdrawed</code>.
     */
    public Byte getWithdrawed() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>pacnode.customer_account.withdrawed</code>.
     */
    public void setWithdrawed(Byte value) {
        set(8, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Integer, Integer, String, String, Byte> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Integer, Integer, String, String, Byte> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CustomerAccount.CUSTOMER_ACCOUNT.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CustomerAccount.CUSTOMER_ACCOUNT.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CustomerAccount.CUSTOMER_ACCOUNT.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CustomerAccount.CUSTOMER_ACCOUNT.REFERRED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return CustomerAccount.CUSTOMER_ACCOUNT.ORIGINAL_INVESTMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return CustomerAccount.CUSTOMER_ACCOUNT.TOTAL_PAID_OUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CustomerAccount.CUSTOMER_ACCOUNT.PAYOUT_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return CustomerAccount.CUSTOMER_ACCOUNT.INVEST_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return CustomerAccount.CUSTOMER_ACCOUNT.WITHDRAWED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getReferredBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getOriginalInvestment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getTotalPaidOut();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPayoutAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getInvestAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getWithdrawed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getReferredBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getOriginalInvestment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getTotalPaidOut();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPayoutAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getInvestAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getWithdrawed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerAccountRecord value1(Integer value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerAccountRecord value2(String value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerAccountRecord value3(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerAccountRecord value4(String value) {
        setReferredBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerAccountRecord value5(Integer value) {
        setOriginalInvestment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerAccountRecord value6(Integer value) {
        setTotalPaidOut(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerAccountRecord value7(String value) {
        setPayoutAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerAccountRecord value8(String value) {
        setInvestAddress(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerAccountRecord value9(Byte value) {
        setWithdrawed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerAccountRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Integer value6, String value7, String value8, Byte value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }
}
