/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.MasternodeCustomers;
import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;
import java.sql.Date;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MasternodeCustomersRecord extends TableRecordImpl<MasternodeCustomersRecord> implements Record7<String, String, Integer, String, Date, Date, Integer> {

    private static final long serialVersionUID = -1477270544;

    /**
     * Create a detached MasternodeCustomersRecord
     */
    public MasternodeCustomersRecord() {
        super(MasternodeCustomers.MASTERNODE_CUSTOMERS);
    }

    /**
     * Create a detached, initialised MasternodeCustomersRecord
     */
    public MasternodeCustomersRecord(String name, String receiveAddress, Integer originalInvestment, String active, Date joinedDate, Date terminatedDate, Integer currentInvestment) {
        super(MasternodeCustomers.MASTERNODE_CUSTOMERS);

        set(0, name);
        set(1, receiveAddress);
        set(2, originalInvestment);
        set(3, active);
        set(4, joinedDate);
        set(5, terminatedDate);
        set(6, currentInvestment);
    }

    /**
     * Getter for <code>pacnode.masternode_customers.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pacnode.masternode_customers.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.masternode_customers.receive_address</code>.
     */
    public String getReceiveAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pacnode.masternode_customers.receive_address</code>.
     */
    public void setReceiveAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pacnode.masternode_customers.original_investment</code>.
     */
    public Integer getOriginalInvestment() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>pacnode.masternode_customers.original_investment</code>.
     */
    public void setOriginalInvestment(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>pacnode.masternode_customers.active</code>.
     */
    public String getActive() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pacnode.masternode_customers.active</code>.
     */
    public void setActive(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pacnode.masternode_customers.joined_date</code>.
     */
    public Date getJoinedDate() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>pacnode.masternode_customers.joined_date</code>.
     */
    public void setJoinedDate(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>pacnode.masternode_customers.terminated_date</code>.
     */
    public Date getTerminatedDate() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>pacnode.masternode_customers.terminated_date</code>.
     */
    public void setTerminatedDate(Date value) {
        set(5, value);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.masternode_customers.current_investment</code>.
     */
    public Integer getCurrentInvestment() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>pacnode.masternode_customers.current_investment</code>.
     */
    public void setCurrentInvestment(Integer value) {
        set(6, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Integer, String, Date, Date, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Integer, String, Date, Date, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MasternodeCustomers.MASTERNODE_CUSTOMERS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MasternodeCustomers.MASTERNODE_CUSTOMERS.RECEIVE_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MasternodeCustomers.MASTERNODE_CUSTOMERS.ORIGINAL_INVESTMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MasternodeCustomers.MASTERNODE_CUSTOMERS.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return MasternodeCustomers.MASTERNODE_CUSTOMERS.JOINED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return MasternodeCustomers.MASTERNODE_CUSTOMERS.TERMINATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return MasternodeCustomers.MASTERNODE_CUSTOMERS.CURRENT_INVESTMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getReceiveAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getOriginalInvestment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component5() {
        return getJoinedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component6() {
        return getTerminatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getCurrentInvestment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReceiveAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOriginalInvestment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getJoinedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getTerminatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getCurrentInvestment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeCustomersRecord value1(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeCustomersRecord value2(String value) {
        setReceiveAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeCustomersRecord value3(Integer value) {
        setOriginalInvestment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeCustomersRecord value4(String value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeCustomersRecord value5(Date value) {
        setJoinedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeCustomersRecord value6(Date value) {
        setTerminatedDate(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeCustomersRecord value7(Integer value) {
        setCurrentInvestment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeCustomersRecord values(String value1, String value2, Integer value3, String value4, Date value5, Date value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }
}
