/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.MasternodeAll;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MasternodeAllRecord extends UpdatableRecordImpl<MasternodeAllRecord> implements Record9<String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -475274350;

    /**
     * Create a detached MasternodeAllRecord
     */
    public MasternodeAllRecord() {
        super(MasternodeAll.MASTERNODE_ALL);
    }

    /**
     * Create a detached, initialised MasternodeAllRecord
     */
    public MasternodeAllRecord(String colTxid, String status, String protocol, String payee, String lastseen, String activeseconds, String lastpaidtime, String lastpaidblock, String ip) {
        super(MasternodeAll.MASTERNODE_ALL);

        set(0, colTxid);
        set(1, status);
        set(2, protocol);
        set(3, payee);
        set(4, lastseen);
        set(5, activeseconds);
        set(6, lastpaidtime);
        set(7, lastpaidblock);
        set(8, ip);
    }

    /**
     * Getter for <code>pacnode.masternode_all.col_txid</code>.
     */
    public String getColTxid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pacnode.masternode_all.col_txid</code>.
     */
    public void setColTxid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.masternode_all.status</code>.
     */
    public String getStatus() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pacnode.masternode_all.status</code>.
     */
    public void setStatus(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pacnode.masternode_all.protocol</code>.
     */
    public String getProtocol() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pacnode.masternode_all.protocol</code>.
     */
    public void setProtocol(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pacnode.masternode_all.payee</code>.
     */
    public String getPayee() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pacnode.masternode_all.payee</code>.
     */
    public void setPayee(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pacnode.masternode_all.lastseen</code>.
     */
    public String getLastseen() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pacnode.masternode_all.lastseen</code>.
     */
    public void setLastseen(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pacnode.masternode_all.activeseconds</code>.
     */
    public String getActiveseconds() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pacnode.masternode_all.activeseconds</code>.
     */
    public void setActiveseconds(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pacnode.masternode_all.lastpaidtime</code>.
     */
    public String getLastpaidtime() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pacnode.masternode_all.lastpaidtime</code>.
     */
    public void setLastpaidtime(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pacnode.masternode_all.lastpaidblock</code>.
     */
    public String getLastpaidblock() {
        return (String) get(7);
    }

    /**
     * Setter for <code>pacnode.masternode_all.lastpaidblock</code>.
     */
    public void setLastpaidblock(String value) {
        set(7, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.masternode_all.IP</code>.
     */
    public String getIp() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>pacnode.masternode_all.IP</code>.
     */
    public void setIp(String value) {
        set(8, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MasternodeAll.MASTERNODE_ALL.COL_TXID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MasternodeAll.MASTERNODE_ALL.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MasternodeAll.MASTERNODE_ALL.PROTOCOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MasternodeAll.MASTERNODE_ALL.PAYEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MasternodeAll.MASTERNODE_ALL.LASTSEEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MasternodeAll.MASTERNODE_ALL.ACTIVESECONDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MasternodeAll.MASTERNODE_ALL.LASTPAIDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MasternodeAll.MASTERNODE_ALL.LASTPAIDBLOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return MasternodeAll.MASTERNODE_ALL.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getColTxid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getProtocol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPayee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLastseen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getActiveseconds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLastpaidtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getLastpaidblock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getColTxid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getProtocol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPayee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLastseen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getActiveseconds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLastpaidtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLastpaidblock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeAllRecord value1(String value) {
        setColTxid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeAllRecord value2(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeAllRecord value3(String value) {
        setProtocol(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeAllRecord value4(String value) {
        setPayee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeAllRecord value5(String value) {
        setLastseen(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeAllRecord value6(String value) {
        setActiveseconds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeAllRecord value7(String value) {
        setLastpaidtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeAllRecord value8(String value) {
        setLastpaidblock(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeAllRecord value9(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeAllRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }
}
