/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.MasternodePayouts;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MasternodePayoutsRecord extends UpdatableRecordImpl<MasternodePayoutsRecord> implements Record6<Integer, Date, Double, Double, Timestamp, BigDecimal> {

    private static final long serialVersionUID = 213644603;

    /**
     * Create a detached MasternodePayoutsRecord
     */
    public MasternodePayoutsRecord() {
        super(MasternodePayouts.MASTERNODE_PAYOUTS);
    }

    /**
     * Create a detached, initialised MasternodePayoutsRecord
     */
    public MasternodePayoutsRecord(Integer mnId, Date payoutDate, Double totalServerFees, Double totalPacnodeFees, Timestamp insertedDate, BigDecimal totalRewards) {
        super(MasternodePayouts.MASTERNODE_PAYOUTS);

        set(0, mnId);
        set(1, payoutDate);
        set(2, totalServerFees);
        set(3, totalPacnodeFees);
        set(4, insertedDate);
        set(5, totalRewards);
    }

    /**
     * Getter for <code>pacnode.masternode_payouts.mn_id</code>.
     */
    public Integer getMnId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pacnode.masternode_payouts.mn_id</code>.
     */
    public void setMnId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.masternode_payouts.payout_date</code>.
     */
    public Date getPayoutDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>pacnode.masternode_payouts.payout_date</code>.
     */
    public void setPayoutDate(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>pacnode.masternode_payouts.total_server_fees</code>.
     */
    public Double getTotalServerFees() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>pacnode.masternode_payouts.total_server_fees</code>.
     */
    public void setTotalServerFees(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>pacnode.masternode_payouts.total_pacnode_fees</code>.
     */
    public Double getTotalPacnodeFees() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>pacnode.masternode_payouts.total_pacnode_fees</code>.
     */
    public void setTotalPacnodeFees(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>pacnode.masternode_payouts.inserted_date</code>.
     */
    public Timestamp getInsertedDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>pacnode.masternode_payouts.inserted_date</code>.
     */
    public void setInsertedDate(Timestamp value) {
        set(4, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.masternode_payouts.total_rewards</code>.
     */
    public BigDecimal getTotalRewards() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>pacnode.masternode_payouts.total_rewards</code>.
     */
    public void setTotalRewards(BigDecimal value) {
        set(5, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Date> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Date, Double, Double, Timestamp, BigDecimal> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Date, Double, Double, Timestamp, BigDecimal> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MasternodePayouts.MASTERNODE_PAYOUTS.MN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return MasternodePayouts.MASTERNODE_PAYOUTS.PAYOUT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return MasternodePayouts.MASTERNODE_PAYOUTS.TOTAL_SERVER_FEES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return MasternodePayouts.MASTERNODE_PAYOUTS.TOTAL_PACNODE_FEES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return MasternodePayouts.MASTERNODE_PAYOUTS.INSERTED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return MasternodePayouts.MASTERNODE_PAYOUTS.TOTAL_REWARDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getPayoutDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getTotalServerFees();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getTotalPacnodeFees();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getInsertedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getTotalRewards();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getPayoutDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getTotalServerFees();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getTotalPacnodeFees();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getInsertedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getTotalRewards();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodePayoutsRecord value1(Integer value) {
        setMnId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodePayoutsRecord value2(Date value) {
        setPayoutDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodePayoutsRecord value3(Double value) {
        setTotalServerFees(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodePayoutsRecord value4(Double value) {
        setTotalPacnodeFees(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodePayoutsRecord value5(Timestamp value) {
        setInsertedDate(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodePayoutsRecord value6(BigDecimal value) {
        setTotalRewards(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodePayoutsRecord values(Integer value1, Date value2, Double value3, Double value4, Timestamp value5, BigDecimal value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }
}
