/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.MasternodeList;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MasternodeListRecord extends UpdatableRecordImpl<MasternodeListRecord> implements Record11<Integer, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1726490459;

    /**
     * Create a detached MasternodeListRecord
     */
    public MasternodeListRecord() {
        super(MasternodeList.MASTERNODE_LIST);
    }

    /**
     * Create a detached, initialised MasternodeListRecord
     */
    public MasternodeListRecord(Integer mnId, String mnLabel, String colTxid, String status, String protocol, String payee, String lastseen, String activeseconds, String lastpaidtime, String lastpaidblock, String ip) {
        super(MasternodeList.MASTERNODE_LIST);

        set(0, mnId);
        set(1, mnLabel);
        set(2, colTxid);
        set(3, status);
        set(4, protocol);
        set(5, payee);
        set(6, lastseen);
        set(7, activeseconds);
        set(8, lastpaidtime);
        set(9, lastpaidblock);
        set(10, ip);
    }

    /**
     * Getter for <code>pacnode.masternode_list.mn_id</code>.
     */
    public Integer getMnId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pacnode.masternode_list.mn_id</code>.
     */
    public void setMnId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.masternode_list.mn_label</code>.
     */
    public String getMnLabel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pacnode.masternode_list.mn_label</code>.
     */
    public void setMnLabel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pacnode.masternode_list.col_txid</code>.
     */
    public String getColTxid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pacnode.masternode_list.col_txid</code>.
     */
    public void setColTxid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pacnode.masternode_list.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pacnode.masternode_list.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pacnode.masternode_list.protocol</code>.
     */
    public String getProtocol() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pacnode.masternode_list.protocol</code>.
     */
    public void setProtocol(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pacnode.masternode_list.payee</code>.
     */
    public String getPayee() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pacnode.masternode_list.payee</code>.
     */
    public void setPayee(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pacnode.masternode_list.lastseen</code>.
     */
    public String getLastseen() {
        return (String) get(6);
    }

    /**
     * Setter for <code>pacnode.masternode_list.lastseen</code>.
     */
    public void setLastseen(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>pacnode.masternode_list.activeseconds</code>.
     */
    public String getActiveseconds() {
        return (String) get(7);
    }

    /**
     * Setter for <code>pacnode.masternode_list.activeseconds</code>.
     */
    public void setActiveseconds(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pacnode.masternode_list.lastpaidtime</code>.
     */
    public String getLastpaidtime() {
        return (String) get(8);
    }

    /**
     * Setter for <code>pacnode.masternode_list.lastpaidtime</code>.
     */
    public void setLastpaidtime(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>pacnode.masternode_list.lastpaidblock</code>.
     */
    public String getLastpaidblock() {
        return (String) get(9);
    }

    /**
     * Setter for <code>pacnode.masternode_list.lastpaidblock</code>.
     */
    public void setLastpaidblock(String value) {
        set(9, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.masternode_list.IP</code>.
     */
    public String getIp() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>pacnode.masternode_list.IP</code>.
     */
    public void setIp(String value) {
        set(10, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MasternodeList.MASTERNODE_LIST.MN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MasternodeList.MASTERNODE_LIST.MN_LABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MasternodeList.MASTERNODE_LIST.COL_TXID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MasternodeList.MASTERNODE_LIST.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MasternodeList.MASTERNODE_LIST.PROTOCOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MasternodeList.MASTERNODE_LIST.PAYEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MasternodeList.MASTERNODE_LIST.LASTSEEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MasternodeList.MASTERNODE_LIST.ACTIVESECONDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return MasternodeList.MASTERNODE_LIST.LASTPAIDTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return MasternodeList.MASTERNODE_LIST.LASTPAIDBLOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return MasternodeList.MASTERNODE_LIST.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMnLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getColTxid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getProtocol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPayee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLastseen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getActiveseconds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getLastpaidtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getLastpaidblock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMnLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getColTxid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getProtocol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPayee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLastseen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getActiveseconds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getLastpaidtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getLastpaidblock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeListRecord value1(Integer value) {
        setMnId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeListRecord value2(String value) {
        setMnLabel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeListRecord value3(String value) {
        setColTxid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeListRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeListRecord value5(String value) {
        setProtocol(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeListRecord value6(String value) {
        setPayee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeListRecord value7(String value) {
        setLastseen(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeListRecord value8(String value) {
        setActiveseconds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeListRecord value9(String value) {
        setLastpaidtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeListRecord value10(String value) {
        setLastpaidblock(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeListRecord value11(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MasternodeListRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }
}
