/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.PacnodePayouts;
import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.sql.Date;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PacnodePayoutsRecord extends TableRecordImpl<PacnodePayoutsRecord> implements Record4<Integer, BigDecimal, Date, BigDecimal> {

    private static final long serialVersionUID = -779484121;

    /**
     * Create a detached PacnodePayoutsRecord
     */
    public PacnodePayoutsRecord() {
        super(PacnodePayouts.PACNODE_PAYOUTS);
    }

    /**
     * Create a detached, initialised PacnodePayoutsRecord
     */
    public PacnodePayoutsRecord(Integer mnId, BigDecimal pacnodeFees, Date payoutDate, BigDecimal netPayout) {
        super(PacnodePayouts.PACNODE_PAYOUTS);

        set(0, mnId);
        set(1, pacnodeFees);
        set(2, payoutDate);
        set(3, netPayout);
    }

    /**
     * Getter for <code>pacnode.pacnode_payouts.mn_id</code>.
     */
    public Integer getMnId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pacnode.pacnode_payouts.mn_id</code>.
     */
    public void setMnId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.pacnode_payouts.pacnode_fees</code>.
     */
    public BigDecimal getPacnodeFees() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>pacnode.pacnode_payouts.pacnode_fees</code>.
     */
    public void setPacnodeFees(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>pacnode.pacnode_payouts.payout_date</code>.
     */
    public Date getPayoutDate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>pacnode.pacnode_payouts.payout_date</code>.
     */
    public void setPayoutDate(Date value) {
        set(2, value);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.pacnode_payouts.net_payout</code>.
     */
    public BigDecimal getNetPayout() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>pacnode.pacnode_payouts.net_payout</code>.
     */
    public void setNetPayout(BigDecimal value) {
        set(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, BigDecimal, Date, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, BigDecimal, Date, BigDecimal> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PacnodePayouts.PACNODE_PAYOUTS.MN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return PacnodePayouts.PACNODE_PAYOUTS.PACNODE_FEES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return PacnodePayouts.PACNODE_PAYOUTS.PAYOUT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return PacnodePayouts.PACNODE_PAYOUTS.NET_PAYOUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getPacnodeFees();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component3() {
        return getPayoutDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getNetPayout();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getPacnodeFees();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getPayoutDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getNetPayout();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacnodePayoutsRecord value1(Integer value) {
        setMnId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacnodePayoutsRecord value2(BigDecimal value) {
        setPacnodeFees(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacnodePayoutsRecord value3(Date value) {
        setPayoutDate(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public PacnodePayoutsRecord value4(BigDecimal value) {
        setNetPayout(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacnodePayoutsRecord values(Integer value1, BigDecimal value2, Date value3, BigDecimal value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
