/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.PacPropVotingHistory;
import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PacPropVotingHistoryRecord extends TableRecordImpl<PacPropVotingHistoryRecord> implements Record7<Timestamp, Integer, String, Byte, Byte, Byte, Timestamp> {

    private static final long serialVersionUID = 1757704288;

    /**
     * Create a detached PacPropVotingHistoryRecord
     */
    public PacPropVotingHistoryRecord() {
        super(PacPropVotingHistory.PAC_PROP_VOTING_HISTORY);
    }

    /**
     * Create a detached, initialised PacPropVotingHistoryRecord
     */
    public PacPropVotingHistoryRecord(Timestamp dtDatetime, Integer accountId, String hash, Byte yes, Byte no, Byte abstain, Timestamp firstVoteDate) {
        super(PacPropVotingHistory.PAC_PROP_VOTING_HISTORY);

        set(0, dtDatetime);
        set(1, accountId);
        set(2, hash);
        set(3, yes);
        set(4, no);
        set(5, abstain);
        set(6, firstVoteDate);
    }

    /**
     * Getter for <code>pacnode.pac_prop_voting_history.dt_datetime</code>.
     */
    public Timestamp getDtDatetime() {
        return (Timestamp) get(0);
    }

    /**
     * Setter for <code>pacnode.pac_prop_voting_history.dt_datetime</code>.
     */
    public void setDtDatetime(Timestamp value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.pac_prop_voting_history.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>pacnode.pac_prop_voting_history.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>pacnode.pac_prop_voting_history.hash</code>.
     */
    public String getHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pacnode.pac_prop_voting_history.hash</code>.
     */
    public void setHash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pacnode.pac_prop_voting_history.yes</code>.
     */
    public Byte getYes() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>pacnode.pac_prop_voting_history.yes</code>.
     */
    public void setYes(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>pacnode.pac_prop_voting_history.no</code>.
     */
    public Byte getNo() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>pacnode.pac_prop_voting_history.no</code>.
     */
    public void setNo(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>pacnode.pac_prop_voting_history.abstain</code>.
     */
    public Byte getAbstain() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>pacnode.pac_prop_voting_history.abstain</code>.
     */
    public void setAbstain(Byte value) {
        set(5, value);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.pac_prop_voting_history.first_vote_date</code>.
     */
    public Timestamp getFirstVoteDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>pacnode.pac_prop_voting_history.first_vote_date</code>.
     */
    public void setFirstVoteDate(Timestamp value) {
        set(6, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Timestamp, Integer, String, Byte, Byte, Byte, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Timestamp, Integer, String, Byte, Byte, Byte, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return PacPropVotingHistory.PAC_PROP_VOTING_HISTORY.DT_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PacPropVotingHistory.PAC_PROP_VOTING_HISTORY.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PacPropVotingHistory.PAC_PROP_VOTING_HISTORY.HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return PacPropVotingHistory.PAC_PROP_VOTING_HISTORY.YES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return PacPropVotingHistory.PAC_PROP_VOTING_HISTORY.NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return PacPropVotingHistory.PAC_PROP_VOTING_HISTORY.ABSTAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return PacPropVotingHistory.PAC_PROP_VOTING_HISTORY.FIRST_VOTE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component1() {
        return getDtDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getYes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getAbstain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getFirstVoteDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getDtDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getYes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getAbstain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getFirstVoteDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacPropVotingHistoryRecord value1(Timestamp value) {
        setDtDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacPropVotingHistoryRecord value2(Integer value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacPropVotingHistoryRecord value3(String value) {
        setHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacPropVotingHistoryRecord value4(Byte value) {
        setYes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacPropVotingHistoryRecord value5(Byte value) {
        setNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacPropVotingHistoryRecord value6(Byte value) {
        setAbstain(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public PacPropVotingHistoryRecord value7(Timestamp value) {
        setFirstVoteDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacPropVotingHistoryRecord values(Timestamp value1, Integer value2, String value3, Byte value4, Byte value5, Byte value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }
}
