/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.PacProposals;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PacProposalsRecord extends UpdatableRecordImpl<PacProposalsRecord> implements Record20<String, String, String, String, Double, Timestamp, Timestamp, Timestamp, String, Integer, Integer, Integer, Integer, Byte, String, Byte, Byte, Byte, Byte, Integer> {

    private static final long serialVersionUID = 230036149;

    /**
     * Create a detached PacProposalsRecord
     */
    public PacProposalsRecord() {
        super(PacProposals.PAC_PROPOSALS);
    }

    /**
     * Create a detached, initialised PacProposalsRecord
     */
    public PacProposalsRecord(String hash, String name, String colhash, String paymentAddr, Double amount, Timestamp startDate, Timestamp endDate, Timestamp createDate, String url, Integer absYesCount, Integer yesCount, Integer noCount, Integer abstainCount, Byte blockValid, String validReason, Byte cachedValid, Byte cachedFunding, Byte cachedDelete, Byte cachedEndorsed, Integer cycles) {
        super(PacProposals.PAC_PROPOSALS);

        set(0, hash);
        set(1, name);
        set(2, colhash);
        set(3, paymentAddr);
        set(4, amount);
        set(5, startDate);
        set(6, endDate);
        set(7, createDate);
        set(8, url);
        set(9, absYesCount);
        set(10, yesCount);
        set(11, noCount);
        set(12, abstainCount);
        set(13, blockValid);
        set(14, validReason);
        set(15, cachedValid);
        set(16, cachedFunding);
        set(17, cachedDelete);
        set(18, cachedEndorsed);
        set(19, cycles);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.hash</code>.
     */
    public String getHash() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.hash</code>.
     */
    public void setHash(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.colhash</code>.
     */
    public String getColhash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.colhash</code>.
     */
    public void setColhash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.payment_addr</code>.
     */
    public String getPaymentAddr() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.payment_addr</code>.
     */
    public void setPaymentAddr(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.amount</code>.
     */
    public void setAmount(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.start_date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.start_date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.end_date</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.end_date</code>.
     */
    public void setEndDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.create_date</code>.
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.create_date</code>.
     */
    public void setCreateDate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.url</code>.
     */
    public String getUrl() {
        return (String) get(8);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.url</code>.
     */
    public void setUrl(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.abs_yes_count</code>.
     */
    public Integer getAbsYesCount() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.abs_yes_count</code>.
     */
    public void setAbsYesCount(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.yes_count</code>.
     */
    public Integer getYesCount() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.yes_count</code>.
     */
    public void setYesCount(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.no_count</code>.
     */
    public Integer getNoCount() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.no_count</code>.
     */
    public void setNoCount(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.abstain_count</code>.
     */
    public Integer getAbstainCount() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.abstain_count</code>.
     */
    public void setAbstainCount(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.block_valid</code>.
     */
    public Byte getBlockValid() {
        return (Byte) get(13);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.block_valid</code>.
     */
    public void setBlockValid(Byte value) {
        set(13, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.valid_reason</code>.
     */
    public String getValidReason() {
        return (String) get(14);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.valid_reason</code>.
     */
    public void setValidReason(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.cached_valid</code>.
     */
    public Byte getCachedValid() {
        return (Byte) get(15);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.cached_valid</code>.
     */
    public void setCachedValid(Byte value) {
        set(15, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.cached_funding</code>.
     */
    public Byte getCachedFunding() {
        return (Byte) get(16);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.cached_funding</code>.
     */
    public void setCachedFunding(Byte value) {
        set(16, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.cached_delete</code>.
     */
    public Byte getCachedDelete() {
        return (Byte) get(17);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.cached_delete</code>.
     */
    public void setCachedDelete(Byte value) {
        set(17, value);
    }

    /**
     * Getter for <code>pacnode.pac_proposals.cached_endorsed</code>.
     */
    public Byte getCachedEndorsed() {
        return (Byte) get(18);
    }

    /**
     * Setter for <code>pacnode.pac_proposals.cached_endorsed</code>.
     */
    public void setCachedEndorsed(Byte value) {
        set(18, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.pac_proposals.cycles</code>.
     */
    public Integer getCycles() {
        return (Integer) get(19);
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>pacnode.pac_proposals.cycles</code>.
     */
    public void setCycles(Integer value) {
        set(19, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<String, String, String, String, Double, Timestamp, Timestamp, Timestamp, String, Integer, Integer, Integer, Integer, Byte, String, Byte, Byte, Byte, Byte, Integer> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<String, String, String, String, Double, Timestamp, Timestamp, Timestamp, String, Integer, Integer, Integer, Integer, Byte, String, Byte, Byte, Byte, Byte, Integer> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return PacProposals.PAC_PROPOSALS.HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PacProposals.PAC_PROPOSALS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PacProposals.PAC_PROPOSALS.COLHASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PacProposals.PAC_PROPOSALS.PAYMENT_ADDR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return PacProposals.PAC_PROPOSALS.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return PacProposals.PAC_PROPOSALS.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return PacProposals.PAC_PROPOSALS.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return PacProposals.PAC_PROPOSALS.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return PacProposals.PAC_PROPOSALS.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return PacProposals.PAC_PROPOSALS.ABS_YES_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return PacProposals.PAC_PROPOSALS.YES_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return PacProposals.PAC_PROPOSALS.NO_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return PacProposals.PAC_PROPOSALS.ABSTAIN_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field14() {
        return PacProposals.PAC_PROPOSALS.BLOCK_VALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return PacProposals.PAC_PROPOSALS.VALID_REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field16() {
        return PacProposals.PAC_PROPOSALS.CACHED_VALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field17() {
        return PacProposals.PAC_PROPOSALS.CACHED_FUNDING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field18() {
        return PacProposals.PAC_PROPOSALS.CACHED_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field19() {
        return PacProposals.PAC_PROPOSALS.CACHED_ENDORSED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field20() {
        return PacProposals.PAC_PROPOSALS.CYCLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getColhash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPaymentAddr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getAbsYesCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getYesCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getNoCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getAbstainCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component14() {
        return getBlockValid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getValidReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component16() {
        return getCachedValid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component17() {
        return getCachedFunding();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component18() {
        return getCachedDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component19() {
        return getCachedEndorsed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component20() {
        return getCycles();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getColhash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPaymentAddr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getAbsYesCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getYesCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getNoCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getAbstainCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value14() {
        return getBlockValid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getValidReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value16() {
        return getCachedValid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value17() {
        return getCachedFunding();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value18() {
        return getCachedDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value19() {
        return getCachedEndorsed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value20() {
        return getCycles();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value1(String value) {
        setHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value3(String value) {
        setColhash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value4(String value) {
        setPaymentAddr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value5(Double value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value6(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value7(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value8(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value9(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value10(Integer value) {
        setAbsYesCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value11(Integer value) {
        setYesCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value12(Integer value) {
        setNoCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value13(Integer value) {
        setAbstainCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value14(Byte value) {
        setBlockValid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value15(String value) {
        setValidReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value16(Byte value) {
        setCachedValid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value17(Byte value) {
        setCachedFunding(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value18(Byte value) {
        setCachedDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value19(Byte value) {
        setCachedEndorsed(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord value20(Integer value) {
        setCycles(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PacProposalsRecord values(String value1, String value2, String value3, String value4, Double value5, Timestamp value6, Timestamp value7, Timestamp value8, String value9, Integer value10, Integer value11, Integer value12, Integer value13, Byte value14, String value15, Byte value16, Byte value17, Byte value18, Byte value19, Integer value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }
}
