/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.PropInfoVotes;
import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;
import java.math.BigInteger;
import java.sql.Timestamp;


/**
 * VIEW
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PropInfoVotesRecord extends TableRecordImpl<PropInfoVotesRecord> implements Record11<String, String, Double, Integer, Timestamp, Timestamp, Timestamp, String, BigInteger, BigInteger, BigInteger> {

    private static final long serialVersionUID = -1732403598;

    /**
     * Create a detached PropInfoVotesRecord
     */
    public PropInfoVotesRecord() {
        super(PropInfoVotes.PROP_INFO_VOTES);
    }

    /**
     * Create a detached, initialised PropInfoVotesRecord
     */
    public PropInfoVotesRecord(String hash, String name, Double amount, Integer cycles, Timestamp startDate, Timestamp endDate, Timestamp createDate, String url, BigInteger yesCount, BigInteger noCount, BigInteger abstainCount) {
        super(PropInfoVotes.PROP_INFO_VOTES);

        set(0, hash);
        set(1, name);
        set(2, amount);
        set(3, cycles);
        set(4, startDate);
        set(5, endDate);
        set(6, createDate);
        set(7, url);
        set(8, yesCount);
        set(9, noCount);
        set(10, abstainCount);
    }

    /**
     * Getter for <code>pacnode.prop_info_votes.hash</code>.
     */
    public String getHash() {
        return (String) get(0);
    }

    /**
     * Setter for <code>pacnode.prop_info_votes.hash</code>.
     */
    public void setHash(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.prop_info_votes.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pacnode.prop_info_votes.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pacnode.prop_info_votes.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>pacnode.prop_info_votes.amount</code>.
     */
    public void setAmount(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>pacnode.prop_info_votes.cycles</code>.
     */
    public Integer getCycles() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>pacnode.prop_info_votes.cycles</code>.
     */
    public void setCycles(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>pacnode.prop_info_votes.start_date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>pacnode.prop_info_votes.start_date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>pacnode.prop_info_votes.end_date</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>pacnode.prop_info_votes.end_date</code>.
     */
    public void setEndDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>pacnode.prop_info_votes.create_date</code>.
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>pacnode.prop_info_votes.create_date</code>.
     */
    public void setCreateDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>pacnode.prop_info_votes.url</code>.
     */
    public String getUrl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>pacnode.prop_info_votes.url</code>.
     */
    public void setUrl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pacnode.prop_info_votes.yes_count</code>.
     */
    public BigInteger getYesCount() {
        return (BigInteger) get(8);
    }

    /**
     * Setter for <code>pacnode.prop_info_votes.yes_count</code>.
     */
    public void setYesCount(BigInteger value) {
        set(8, value);
    }

    /**
     * Getter for <code>pacnode.prop_info_votes.no_count</code>.
     */
    public BigInteger getNoCount() {
        return (BigInteger) get(9);
    }

    /**
     * Setter for <code>pacnode.prop_info_votes.no_count</code>.
     */
    public void setNoCount(BigInteger value) {
        set(9, value);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.prop_info_votes.abstain_count</code>.
     */
    public BigInteger getAbstainCount() {
        return (BigInteger) get(10);
    }

    /**
     * Setter for <code>pacnode.prop_info_votes.abstain_count</code>.
     */
    public void setAbstainCount(BigInteger value) {
        set(10, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, Double, Integer, Timestamp, Timestamp, Timestamp, String, BigInteger, BigInteger, BigInteger> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, Double, Integer, Timestamp, Timestamp, Timestamp, String, BigInteger, BigInteger, BigInteger> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return PropInfoVotes.PROP_INFO_VOTES.HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PropInfoVotes.PROP_INFO_VOTES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return PropInfoVotes.PROP_INFO_VOTES.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PropInfoVotes.PROP_INFO_VOTES.CYCLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return PropInfoVotes.PROP_INFO_VOTES.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return PropInfoVotes.PROP_INFO_VOTES.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return PropInfoVotes.PROP_INFO_VOTES.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return PropInfoVotes.PROP_INFO_VOTES.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field9() {
        return PropInfoVotes.PROP_INFO_VOTES.YES_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field10() {
        return PropInfoVotes.PROP_INFO_VOTES.NO_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field11() {
        return PropInfoVotes.PROP_INFO_VOTES.ABSTAIN_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCycles();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component9() {
        return getYesCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component10() {
        return getNoCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component11() {
        return getAbstainCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCycles();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value9() {
        return getYesCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value10() {
        return getNoCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value11() {
        return getAbstainCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropInfoVotesRecord value1(String value) {
        setHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropInfoVotesRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropInfoVotesRecord value3(Double value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropInfoVotesRecord value4(Integer value) {
        setCycles(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropInfoVotesRecord value5(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropInfoVotesRecord value6(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropInfoVotesRecord value7(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropInfoVotesRecord value8(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropInfoVotesRecord value9(BigInteger value) {
        setYesCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropInfoVotesRecord value10(BigInteger value) {
        setNoCount(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public PropInfoVotesRecord value11(BigInteger value) {
        setAbstainCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropInfoVotesRecord values(String value1, String value2, Double value3, Integer value4, Timestamp value5, Timestamp value6, Timestamp value7, String value8, BigInteger value9, BigInteger value10, BigInteger value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }
}
