/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.Referrals;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ReferralsRecord extends UpdatableRecordImpl<ReferralsRecord> implements Record5<Integer, String, String, Integer, BigDecimal> {

    private static final long serialVersionUID = 221375430;

    /**
     * Create a detached ReferralsRecord
     */
    public ReferralsRecord() {
        super(Referrals.REFERRALS);
    }

    /**
     * Create a detached, initialised ReferralsRecord
     */
    public ReferralsRecord(Integer id, String accountName, String referralCode, Integer totalReferrals, BigDecimal totalPacPaid) {
        super(Referrals.REFERRALS);

        set(0, id);
        set(1, accountName);
        set(2, referralCode);
        set(3, totalReferrals);
        set(4, totalPacPaid);
    }

    /**
     * Getter for <code>pacnode.referrals.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pacnode.referrals.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.referrals.account_name</code>.
     */
    public String getAccountName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>pacnode.referrals.account_name</code>.
     */
    public void setAccountName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>pacnode.referrals.referral_code</code>.
     */
    public String getReferralCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pacnode.referrals.referral_code</code>.
     */
    public void setReferralCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pacnode.referrals.total_referrals</code>.
     */
    public Integer getTotalReferrals() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>pacnode.referrals.total_referrals</code>.
     */
    public void setTotalReferrals(Integer value) {
        set(3, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.referrals.total_pac_paid</code>.
     */
    public BigDecimal getTotalPacPaid() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>pacnode.referrals.total_pac_paid</code>.
     */
    public void setTotalPacPaid(BigDecimal value) {
        set(4, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Integer, BigDecimal> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Integer, BigDecimal> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Referrals.REFERRALS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Referrals.REFERRALS.ACCOUNT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Referrals.REFERRALS.REFERRAL_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Referrals.REFERRALS.TOTAL_REFERRALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return Referrals.REFERRALS.TOTAL_PAC_PAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAccountName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getReferralCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getTotalReferrals();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getTotalPacPaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAccountName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getReferralCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTotalReferrals();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getTotalPacPaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value2(String value) {
        setAccountName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value3(String value) {
        setReferralCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value4(Integer value) {
        setTotalReferrals(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord value5(BigDecimal value) {
        setTotalPacPaid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReferralsRecord values(Integer value1, String value2, String value3, Integer value4, BigDecimal value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
