/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.VPayoutHistory;
import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * VIEW
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VPayoutHistoryRecord extends TableRecordImpl<VPayoutHistoryRecord> implements Record13<Integer, Integer, Timestamp, Timestamp, Double, Double, Double, String, Timestamp, Byte, String, Long, Byte> {

    private static final long serialVersionUID = 179812808;

    /**
     * Create a detached VPayoutHistoryRecord
     */
    public VPayoutHistoryRecord() {
        super(VPayoutHistory.V_PAYOUT_HISTORY);
    }

    /**
     * Create a detached, initialised VPayoutHistoryRecord
     */
    public VPayoutHistoryRecord(Integer accountId, Integer mnId, Timestamp requestDate, Timestamp sendDate, Double rewardPayout, Double feeAmount, Double serverCostAmount, String payoutAddress, Timestamp insertedDate, Byte paidOut, String transactionId, Long confirmations, Byte reinvest) {
        super(VPayoutHistory.V_PAYOUT_HISTORY);

        set(0, accountId);
        set(1, mnId);
        set(2, requestDate);
        set(3, sendDate);
        set(4, rewardPayout);
        set(5, feeAmount);
        set(6, serverCostAmount);
        set(7, payoutAddress);
        set(8, insertedDate);
        set(9, paidOut);
        set(10, transactionId);
        set(11, confirmations);
        set(12, reinvest);
    }

    /**
     * Getter for <code>pacnode.v_payout_history.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pacnode.v_payout_history.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.v_payout_history.mn_id</code>.
     */
    public Integer getMnId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>pacnode.v_payout_history.mn_id</code>.
     */
    public void setMnId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>pacnode.v_payout_history.request_date</code>.
     */
    public Timestamp getRequestDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>pacnode.v_payout_history.request_date</code>.
     */
    public void setRequestDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>pacnode.v_payout_history.send_date</code>.
     */
    public Timestamp getSendDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>pacnode.v_payout_history.send_date</code>.
     */
    public void setSendDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>pacnode.v_payout_history.reward_payout</code>.
     */
    public Double getRewardPayout() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>pacnode.v_payout_history.reward_payout</code>.
     */
    public void setRewardPayout(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>pacnode.v_payout_history.fee_amount</code>.
     */
    public Double getFeeAmount() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>pacnode.v_payout_history.fee_amount</code>.
     */
    public void setFeeAmount(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>pacnode.v_payout_history.server_cost_amount</code>.
     */
    public Double getServerCostAmount() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>pacnode.v_payout_history.server_cost_amount</code>.
     */
    public void setServerCostAmount(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>pacnode.v_payout_history.payout_address</code>.
     */
    public String getPayoutAddress() {
        return (String) get(7);
    }

    /**
     * Setter for <code>pacnode.v_payout_history.payout_address</code>.
     */
    public void setPayoutAddress(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pacnode.v_payout_history.inserted_date</code>.
     */
    public Timestamp getInsertedDate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>pacnode.v_payout_history.inserted_date</code>.
     */
    public void setInsertedDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>pacnode.v_payout_history.paid_out</code>.
     */
    public Byte getPaidOut() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>pacnode.v_payout_history.paid_out</code>.
     */
    public void setPaidOut(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>pacnode.v_payout_history.transaction_id</code>.
     */
    public String getTransactionId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>pacnode.v_payout_history.transaction_id</code>.
     */
    public void setTransactionId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>pacnode.v_payout_history.confirmations</code>.
     */
    public Long getConfirmations() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>pacnode.v_payout_history.confirmations</code>.
     */
    public void setConfirmations(Long value) {
        set(11, value);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.v_payout_history.reinvest</code>.
     */
    public Byte getReinvest() {
        return (Byte) get(12);
    }

    /**
     * Setter for <code>pacnode.v_payout_history.reinvest</code>.
     */
    public void setReinvest(Byte value) {
        set(12, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, Timestamp, Timestamp, Double, Double, Double, String, Timestamp, Byte, String, Long, Byte> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, Timestamp, Timestamp, Double, Double, Double, String, Timestamp, Byte, String, Long, Byte> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VPayoutHistory.V_PAYOUT_HISTORY.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return VPayoutHistory.V_PAYOUT_HISTORY.MN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return VPayoutHistory.V_PAYOUT_HISTORY.REQUEST_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return VPayoutHistory.V_PAYOUT_HISTORY.SEND_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return VPayoutHistory.V_PAYOUT_HISTORY.REWARD_PAYOUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return VPayoutHistory.V_PAYOUT_HISTORY.FEE_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return VPayoutHistory.V_PAYOUT_HISTORY.SERVER_COST_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return VPayoutHistory.V_PAYOUT_HISTORY.PAYOUT_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return VPayoutHistory.V_PAYOUT_HISTORY.INSERTED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return VPayoutHistory.V_PAYOUT_HISTORY.PAID_OUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return VPayoutHistory.V_PAYOUT_HISTORY.TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return VPayoutHistory.V_PAYOUT_HISTORY.CONFIRMATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field13() {
        return VPayoutHistory.V_PAYOUT_HISTORY.REINVEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getMnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getRequestDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getSendDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getRewardPayout();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getFeeAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getServerCostAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getPayoutAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getInsertedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component10() {
        return getPaidOut();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getConfirmations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component13() {
        return getReinvest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getMnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getRequestDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getSendDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getRewardPayout();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getFeeAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getServerCostAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPayoutAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getInsertedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getPaidOut();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getConfirmations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value13() {
        return getReinvest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistoryRecord value1(Integer value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistoryRecord value2(Integer value) {
        setMnId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistoryRecord value3(Timestamp value) {
        setRequestDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistoryRecord value4(Timestamp value) {
        setSendDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistoryRecord value5(Double value) {
        setRewardPayout(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistoryRecord value6(Double value) {
        setFeeAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistoryRecord value7(Double value) {
        setServerCostAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistoryRecord value8(String value) {
        setPayoutAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistoryRecord value9(Timestamp value) {
        setInsertedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistoryRecord value10(Byte value) {
        setPaidOut(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistoryRecord value11(String value) {
        setTransactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistoryRecord value12(Long value) {
        setConfirmations(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistoryRecord value13(Byte value) {
        setReinvest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VPayoutHistoryRecord values(Integer value1, Integer value2, Timestamp value3, Timestamp value4, Double value5, Double value6, Double value7, String value8, Timestamp value9, Byte value10, String value11, Long value12, Byte value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }
}
