/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model.tables.records;


import com.github.jmart1.example.repo.website.model.tables.WithdrawalRequestsHistory;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WithdrawalRequestsHistoryRecord extends UpdatableRecordImpl<WithdrawalRequestsHistoryRecord> implements Record13<Integer, Integer, Integer, String, String, Integer, Double, Double, Double, Timestamp, Timestamp, String, Timestamp> {

    private static final long serialVersionUID = 2069475803;

    /**
     * Create a detached WithdrawalRequestsHistoryRecord
     */
    public WithdrawalRequestsHistoryRecord() {
        super(WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY);
    }

    /**
     * Create a detached, initialised WithdrawalRequestsHistoryRecord
     */
    public WithdrawalRequestsHistoryRecord(Integer requestId, Integer payoutId, Integer accountId, String payoutAddress, String status, Integer confirmations, Double withdrawalAmount, Double pacnodeFee, Double grossRewards, Timestamp requestDate, Timestamp sendDate, String transactionId, Timestamp historyDate) {
        super(WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY);

        set(0, requestId);
        set(1, payoutId);
        set(2, accountId);
        set(3, payoutAddress);
        set(4, status);
        set(5, confirmations);
        set(6, withdrawalAmount);
        set(7, pacnodeFee);
        set(8, grossRewards);
        set(9, requestDate);
        set(10, sendDate);
        set(11, transactionId);
        set(12, historyDate);
    }

    /**
     * Getter for <code>pacnode.withdrawal_requests_history.request_id</code>.
     */
    public Integer getRequestId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>pacnode.withdrawal_requests_history.request_id</code>.
     */
    public void setRequestId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>pacnode.withdrawal_requests_history.payout_id</code>.
     */
    public Integer getPayoutId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>pacnode.withdrawal_requests_history.payout_id</code>.
     */
    public void setPayoutId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>pacnode.withdrawal_requests_history.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>pacnode.withdrawal_requests_history.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>pacnode.withdrawal_requests_history.payout_address</code>.
     */
    public String getPayoutAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pacnode.withdrawal_requests_history.payout_address</code>.
     */
    public void setPayoutAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pacnode.withdrawal_requests_history.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>pacnode.withdrawal_requests_history.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>pacnode.withdrawal_requests_history.confirmations</code>.
     */
    public Integer getConfirmations() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>pacnode.withdrawal_requests_history.confirmations</code>.
     */
    public void setConfirmations(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>pacnode.withdrawal_requests_history.withdrawal_amount</code>.
     */
    public Double getWithdrawalAmount() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>pacnode.withdrawal_requests_history.withdrawal_amount</code>.
     */
    public void setWithdrawalAmount(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>pacnode.withdrawal_requests_history.pacnode_fee</code>.
     */
    public Double getPacnodeFee() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>pacnode.withdrawal_requests_history.pacnode_fee</code>.
     */
    public void setPacnodeFee(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>pacnode.withdrawal_requests_history.gross_rewards</code>.
     */
    public Double getGrossRewards() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>pacnode.withdrawal_requests_history.gross_rewards</code>.
     */
    public void setGrossRewards(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>pacnode.withdrawal_requests_history.request_date</code>.
     */
    public Timestamp getRequestDate() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>pacnode.withdrawal_requests_history.request_date</code>.
     */
    public void setRequestDate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>pacnode.withdrawal_requests_history.send_date</code>.
     */
    public Timestamp getSendDate() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>pacnode.withdrawal_requests_history.send_date</code>.
     */
    public void setSendDate(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>pacnode.withdrawal_requests_history.transaction_id</code>.
     */
    public String getTransactionId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>pacnode.withdrawal_requests_history.transaction_id</code>.
     */
    public void setTransactionId(String value) {
        set(11, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>pacnode.withdrawal_requests_history.history_date</code>.
     */
    public Timestamp getHistoryDate() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>pacnode.withdrawal_requests_history.history_date</code>.
     */
    public void setHistoryDate(Timestamp value) {
        set(12, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, Integer, String, String, Integer, Double, Double, Double, Timestamp, Timestamp, String, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, Integer, String, String, Integer, Double, Double, Double, Timestamp, Timestamp, String, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.REQUEST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.PAYOUT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.PAYOUT_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.CONFIRMATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.WITHDRAWAL_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.PACNODE_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field9() {
        return WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.GROSS_REWARDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.REQUEST_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.SEND_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.HISTORY_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRequestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPayoutId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPayoutAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getConfirmations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getWithdrawalAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component8() {
        return getPacnodeFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component9() {
        return getGrossRewards();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getRequestDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getSendDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getHistoryDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRequestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPayoutId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPayoutAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getConfirmations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getWithdrawalAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getPacnodeFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value9() {
        return getGrossRewards();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getRequestDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getSendDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getHistoryDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequestsHistoryRecord value1(Integer value) {
        setRequestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequestsHistoryRecord value2(Integer value) {
        setPayoutId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequestsHistoryRecord value3(Integer value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequestsHistoryRecord value4(String value) {
        setPayoutAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequestsHistoryRecord value5(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequestsHistoryRecord value6(Integer value) {
        setConfirmations(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequestsHistoryRecord value7(Double value) {
        setWithdrawalAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequestsHistoryRecord value8(Double value) {
        setPacnodeFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequestsHistoryRecord value9(Double value) {
        setGrossRewards(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequestsHistoryRecord value10(Timestamp value) {
        setRequestDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequestsHistoryRecord value11(Timestamp value) {
        setSendDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequestsHistoryRecord value12(String value) {
        setTransactionId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequestsHistoryRecord value13(Timestamp value) {
        setHistoryDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WithdrawalRequestsHistoryRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Integer value6, Double value7, Double value8, Double value9, Timestamp value10, Timestamp value11, String value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }
}
