/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.service.model.tables;


import com.github.jmart1.example.repo.service.model.Indexes;
import com.github.jmart1.example.repo.service.model.Keys;
import com.github.jmart1.example.repo.service.model.Pacnode;
import com.github.jmart1.example.repo.service.model.tables.records.UserLoginsRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class UserLogins extends TableImpl<UserLoginsRecord> {

    private static final long serialVersionUID = -1178150100;

    /**
     * The reference instance of <code>pacnode.user_logins</code>
     */
    public static final UserLogins USER_LOGINS = new UserLogins();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserLoginsRecord> getRecordType() {
        return UserLoginsRecord.class;
    }

    /**
     * The column <code>pacnode.user_logins.account_id</code>.
     */
    public final TableField<UserLoginsRecord, Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>pacnode.user_logins.password</code>.
     */
    public final TableField<UserLoginsRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>pacnode.user_logins.email_address</code>.
     */
    public final TableField<UserLoginsRecord, String> EMAIL_ADDRESS = createField("email_address", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>pacnode.user_logins</code> table reference
     */
    public UserLogins() {
        this(DSL.name("user_logins"), null);
    }

    /**
     * Create an aliased <code>pacnode.user_logins</code> table reference
     */
    public UserLogins(String alias) {
        this(DSL.name(alias), USER_LOGINS);
    }

    /**
     * Create an aliased <code>pacnode.user_logins</code> table reference
     */
    public UserLogins(Name alias) {
        this(alias, USER_LOGINS);
    }

    private UserLogins(Name alias, Table<UserLoginsRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserLogins(Name alias, Table<UserLoginsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Pacnode.PACNODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_LOGINS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserLoginsRecord> getPrimaryKey() {
        return Keys.KEY_USER_LOGINS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserLoginsRecord>> getKeys() {
        return Arrays.<UniqueKey<UserLoginsRecord>>asList(Keys.KEY_USER_LOGINS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLogins as(String alias) {
        return new UserLogins(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserLogins as(Name alias) {
        return new UserLogins(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserLogins rename(String name) {
        return new UserLogins(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserLogins rename(Name name) {
        return new UserLogins(name, null);
    }
}
