/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.service.model;


import com.github.jmart1.example.repo.service.model.tables.PayoutQueue;
import com.github.jmart1.example.repo.service.model.tables.Transactions;
import com.github.jmart1.example.repo.service.model.tables.CoinUsdPrices;
import com.github.jmart1.example.repo.service.model.tables.UserLogins;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>pacnode</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COIN_USD_PRICES_COIN_NAME = Indexes0.COIN_USD_PRICES_COIN_NAME;
    public static final Index COIN_USD_PRICES_DATE = Indexes0.COIN_USD_PRICES_DATE;
    public static final Index COIN_USD_PRICES_PRIMARY = Indexes0.COIN_USD_PRICES_PRIMARY;
    public static final Index PAYOUT_QUEUE_PRIMARY = Indexes0.PAYOUT_QUEUE_PRIMARY;
    public static final Index PAYOUT_QUEUE_QUEUE_PAYOUT_ADDRESS_IDX = Indexes0.PAYOUT_QUEUE_QUEUE_PAYOUT_ADDRESS_IDX;
    public static final Index TRANSACTIONS_ACCOUNT_GENERATED = Indexes0.TRANSACTIONS_ACCOUNT_GENERATED;
    public static final Index TRANSACTIONS_PRIMARY = Indexes0.TRANSACTIONS_PRIMARY;
    public static final Index USER_LOGINS_PRIMARY = Indexes0.USER_LOGINS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index COIN_USD_PRICES_COIN_NAME = Internal.createIndex("coin_name", CoinUsdPrices.COIN_USD_PRICES, new OrderField[]{CoinUsdPrices.COIN_USD_PRICES.COIN_NAME}, false);
        public static Index COIN_USD_PRICES_DATE = Internal.createIndex("date", CoinUsdPrices.COIN_USD_PRICES, new OrderField[]{CoinUsdPrices.COIN_USD_PRICES.DATE, CoinUsdPrices.COIN_USD_PRICES.COIN_NAME}, false);
        public static Index COIN_USD_PRICES_PRIMARY = Internal.createIndex("PRIMARY", CoinUsdPrices.COIN_USD_PRICES, new OrderField[]{CoinUsdPrices.COIN_USD_PRICES.DATE, CoinUsdPrices.COIN_USD_PRICES.CLOSE, CoinUsdPrices.COIN_USD_PRICES.COIN_NAME}, true);
        public static Index PAYOUT_QUEUE_PRIMARY = Internal.createIndex("PRIMARY", PayoutQueue.PAYOUT_QUEUE, new OrderField[]{PayoutQueue.PAYOUT_QUEUE.PAYOUT_ID}, true);
        public static Index PAYOUT_QUEUE_QUEUE_PAYOUT_ADDRESS_IDX = Internal.createIndex("queue_payout_address_idx", PayoutQueue.PAYOUT_QUEUE, new OrderField[]{PayoutQueue.PAYOUT_QUEUE.PAYOUT_ADDRESS}, false);
        public static Index TRANSACTIONS_ACCOUNT_GENERATED = Internal.createIndex("account_generated", Transactions.TRANSACTIONS, new OrderField[]{Transactions.TRANSACTIONS.ACCOUNT, Transactions.TRANSACTIONS.GENERATED}, false);
        public static Index TRANSACTIONS_PRIMARY = Internal.createIndex("PRIMARY", Transactions.TRANSACTIONS, new OrderField[]{Transactions.TRANSACTIONS.TXID}, true);
        public static Index USER_LOGINS_PRIMARY = Internal.createIndex("PRIMARY", UserLogins.USER_LOGINS, new OrderField[]{UserLogins.USER_LOGINS.ACCOUNT_ID}, true);
    }
}
