/*
 * This file is generated by jOOQ.
*/
package com.github.jmart1.example.repo.service.model;


import com.github.jmart1.example.repo.service.model.tables.CoinUsdPrices;
import com.github.jmart1.example.repo.service.model.tables.PayoutQueue;
import com.github.jmart1.example.repo.service.model.tables.Transactions;
import com.github.jmart1.example.repo.service.model.tables.UserLogins;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pacnode extends SchemaImpl {

    private static final long serialVersionUID = 2011833648;

    /**
     * The reference instance of <code>pacnode</code>
     */
    public static final Pacnode PACNODE = new Pacnode();

    /**
     * The table <code>pacnode.coin_usd_prices</code>.
     */
    public final CoinUsdPrices COIN_USD_PRICES = CoinUsdPrices.COIN_USD_PRICES;

    /**
     * The table <code>pacnode.payout_queue</code>.
     */
    public final PayoutQueue PAYOUT_QUEUE = PayoutQueue.PAYOUT_QUEUE;

    /**
     * The table <code>pacnode.transactions</code>.
     */
    public final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;

    /**
     * The table <code>pacnode.user_logins</code>.
     */
    public final UserLogins USER_LOGINS = UserLogins.USER_LOGINS;

    /**
     * No further instances allowed
     */
    private Pacnode() {
        super("pacnode", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                CoinUsdPrices.COIN_USD_PRICES,
                PayoutQueue.PAYOUT_QUEUE,
                Transactions.TRANSACTIONS,
                UserLogins.USER_LOGINS);
    }
}
