/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.service.model;


import com.github.jmart1.example.repo.service.model.tables.PayoutQueue;
import com.github.jmart1.example.repo.service.model.tables.Transactions;
import com.github.jmart1.example.repo.service.model.tables.CoinUsdPrices;
import com.github.jmart1.example.repo.service.model.tables.UserLogins;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in pacnode
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>pacnode.coin_usd_prices</code>.
     */
    public static final CoinUsdPrices COIN_USD_PRICES = CoinUsdPrices.COIN_USD_PRICES;

    /**
     * The table <code>pacnode.payout_queue</code>.
     */
    public static final PayoutQueue PAYOUT_QUEUE = PayoutQueue.PAYOUT_QUEUE;

    /**
     * The table <code>pacnode.transactions</code>.
     */
    public static final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;

    /**
     * The table <code>pacnode.user_logins</code>.
     */
    public static final UserLogins USER_LOGINS = UserLogins.USER_LOGINS;
}
