/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model;


import com.github.jmart1.example.repo.website.model.tables.*;
import net.pacnode.cronservices.repo.website.model.tables.*;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>pacnode</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNT_MASTERNODE_REWARDS_PRIMARY = Indexes0.ACCOUNT_MASTERNODE_REWARDS_PRIMARY;
    public static final Index CURRENT_ACCOUNT_REWARDS_PRIMARY = Indexes0.CURRENT_ACCOUNT_REWARDS_PRIMARY;
    public static final Index CUSTOMER_ACCOUNT_CUST_ID = Indexes0.CUSTOMER_ACCOUNT_CUST_ID;
    public static final Index CUSTOMER_ACCOUNT_PRIMARY = Indexes0.CUSTOMER_ACCOUNT_PRIMARY;
    public static final Index CUSTOMER_LOGINS_PRIMARY = Indexes0.CUSTOMER_LOGINS_PRIMARY;
    public static final Index CUSTOMER_MASTERNODE_MAPPING_PRIMARY = Indexes0.CUSTOMER_MASTERNODE_MAPPING_PRIMARY;
    public static final Index MASTERNODE_ALL_PRIMARY = Indexes0.MASTERNODE_ALL_PRIMARY;
    public static final Index MASTERNODE_LIST_PRIMARY = Indexes0.MASTERNODE_LIST_PRIMARY;
    public static final Index MASTERNODE_PAYOUTS_PRIMARY = Indexes0.MASTERNODE_PAYOUTS_PRIMARY;
    public static final Index MASTERNODE_TRANSACTIONS_MN_TRANS_ID = Indexes0.MASTERNODE_TRANSACTIONS_MN_TRANS_ID;
    public static final Index MASTERNODE_TRANSACTIONS_PRIMARY = Indexes0.MASTERNODE_TRANSACTIONS_PRIMARY;
    public static final Index PAC_PROPOSALS_PRIMARY = Indexes0.PAC_PROPOSALS_PRIMARY;
    public static final Index PAC_PROP_VOTING_PRIMARY = Indexes0.PAC_PROP_VOTING_PRIMARY;
    public static final Index REFERRALS_PRIMARY = Indexes0.REFERRALS_PRIMARY;
    public static final Index WITHDRAWAL_REQUESTS_ACCOUNT_IDX = Indexes0.WITHDRAWAL_REQUESTS_ACCOUNT_IDX;
    public static final Index WITHDRAWAL_REQUESTS_PAYOUT_ADDRESS_IDX = Indexes0.WITHDRAWAL_REQUESTS_PAYOUT_ADDRESS_IDX;
    public static final Index WITHDRAWAL_REQUESTS_PRIMARY = Indexes0.WITHDRAWAL_REQUESTS_PRIMARY;
    public static final Index WITHDRAWAL_REQUESTS_HISTORY_ACCOUNT_IDX = Indexes0.WITHDRAWAL_REQUESTS_HISTORY_ACCOUNT_IDX;
    public static final Index WITHDRAWAL_REQUESTS_HISTORY_PAYOUT_ADDRESS_IDX = Indexes0.WITHDRAWAL_REQUESTS_HISTORY_PAYOUT_ADDRESS_IDX;
    public static final Index WITHDRAWAL_REQUESTS_HISTORY_PRIMARY = Indexes0.WITHDRAWAL_REQUESTS_HISTORY_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNT_MASTERNODE_REWARDS_PRIMARY = Internal.createIndex("PRIMARY", AccountMasternodeRewards.ACCOUNT_MASTERNODE_REWARDS, new OrderField[]{AccountMasternodeRewards.ACCOUNT_MASTERNODE_REWARDS.ACCOUNT_ID, AccountMasternodeRewards.ACCOUNT_MASTERNODE_REWARDS.MN_ID}, true);
        public static Index CURRENT_ACCOUNT_REWARDS_PRIMARY = Internal.createIndex("PRIMARY", CurrentAccountRewards.CURRENT_ACCOUNT_REWARDS, new OrderField[]{CurrentAccountRewards.CURRENT_ACCOUNT_REWARDS.ACCOUNT_ID}, true);
        public static Index CUSTOMER_ACCOUNT_CUST_ID = Internal.createIndex("cust_id", CustomerAccount.CUSTOMER_ACCOUNT, new OrderField[]{CustomerAccount.CUSTOMER_ACCOUNT.ACCOUNT_ID}, true);
        public static Index CUSTOMER_ACCOUNT_PRIMARY = Internal.createIndex("PRIMARY", CustomerAccount.CUSTOMER_ACCOUNT, new OrderField[]{CustomerAccount.CUSTOMER_ACCOUNT.UUID}, true);
        public static Index CUSTOMER_LOGINS_PRIMARY = Internal.createIndex("PRIMARY", CustomerLogins.CUSTOMER_LOGINS, new OrderField[]{CustomerLogins.CUSTOMER_LOGINS.ACCOUNT_ID}, true);
        public static Index CUSTOMER_MASTERNODE_MAPPING_PRIMARY = Internal.createIndex("PRIMARY", CustomerMasternodeMapping.CUSTOMER_MASTERNODE_MAPPING, new OrderField[]{CustomerMasternodeMapping.CUSTOMER_MASTERNODE_MAPPING.ACCOUNT_ID, CustomerMasternodeMapping.CUSTOMER_MASTERNODE_MAPPING.MN_ID}, true);
        public static Index MASTERNODE_ALL_PRIMARY = Internal.createIndex("PRIMARY", MasternodeAll.MASTERNODE_ALL, new OrderField[]{MasternodeAll.MASTERNODE_ALL.COL_TXID}, true);
        public static Index MASTERNODE_LIST_PRIMARY = Internal.createIndex("PRIMARY", MasternodeList.MASTERNODE_LIST, new OrderField[]{MasternodeList.MASTERNODE_LIST.MN_ID}, true);
        public static Index MASTERNODE_PAYOUTS_PRIMARY = Internal.createIndex("PRIMARY", MasternodePayouts.MASTERNODE_PAYOUTS, new OrderField[]{MasternodePayouts.MASTERNODE_PAYOUTS.MN_ID, MasternodePayouts.MASTERNODE_PAYOUTS.PAYOUT_DATE}, true);
        public static Index MASTERNODE_TRANSACTIONS_MN_TRANS_ID = Internal.createIndex("mn_trans_id", MasternodeTransactions.MASTERNODE_TRANSACTIONS, new OrderField[]{MasternodeTransactions.MASTERNODE_TRANSACTIONS.MN_ID}, false);
        public static Index MASTERNODE_TRANSACTIONS_PRIMARY = Internal.createIndex("PRIMARY", MasternodeTransactions.MASTERNODE_TRANSACTIONS, new OrderField[]{MasternodeTransactions.MASTERNODE_TRANSACTIONS.MN_ID, MasternodeTransactions.MASTERNODE_TRANSACTIONS.PAYOUT_ADDRESS, MasternodeTransactions.MASTERNODE_TRANSACTIONS.TRANSACTION_ID}, true);
        public static Index PAC_PROPOSALS_PRIMARY = Internal.createIndex("PRIMARY", PacProposals.PAC_PROPOSALS, new OrderField[]{PacProposals.PAC_PROPOSALS.HASH}, true);
        public static Index PAC_PROP_VOTING_PRIMARY = Internal.createIndex("PRIMARY", PacPropVoting.PAC_PROP_VOTING, new OrderField[]{PacPropVoting.PAC_PROP_VOTING.ACCOUNT_ID, PacPropVoting.PAC_PROP_VOTING.HASH}, true);
        public static Index REFERRALS_PRIMARY = Internal.createIndex("PRIMARY", Referrals.REFERRALS, new OrderField[]{Referrals.REFERRALS.ID}, true);
        public static Index WITHDRAWAL_REQUESTS_ACCOUNT_IDX = Internal.createIndex("account_idx", WithdrawalRequests.WITHDRAWAL_REQUESTS, new OrderField[]{WithdrawalRequests.WITHDRAWAL_REQUESTS.ACCOUNT_ID}, false);
        public static Index WITHDRAWAL_REQUESTS_PAYOUT_ADDRESS_IDX = Internal.createIndex("payout_address_idx", WithdrawalRequests.WITHDRAWAL_REQUESTS, new OrderField[]{WithdrawalRequests.WITHDRAWAL_REQUESTS.PAYOUT_ADDRESS}, false);
        public static Index WITHDRAWAL_REQUESTS_PRIMARY = Internal.createIndex("PRIMARY", WithdrawalRequests.WITHDRAWAL_REQUESTS, new OrderField[]{WithdrawalRequests.WITHDRAWAL_REQUESTS.REQUEST_ID}, true);
        public static Index WITHDRAWAL_REQUESTS_HISTORY_ACCOUNT_IDX = Internal.createIndex("account_idx", WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY, new OrderField[]{WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.ACCOUNT_ID}, false);
        public static Index WITHDRAWAL_REQUESTS_HISTORY_PAYOUT_ADDRESS_IDX = Internal.createIndex("payout_address_idx", WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY, new OrderField[]{WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.PAYOUT_ADDRESS}, false);
        public static Index WITHDRAWAL_REQUESTS_HISTORY_PRIMARY = Internal.createIndex("PRIMARY", WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY, new OrderField[]{WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.REQUEST_ID}, true);
    }
}
