/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model;


import com.github.jmart1.example.repo.website.model.tables.*;
import com.github.jmart1.example.repo.website.model.tables.records.*;
import net.pacnode.cronservices.repo.website.model.tables.*;
import net.pacnode.cronservices.repo.website.model.tables.records.*;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code>pacnode</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CustomerAccountRecord, Integer> IDENTITY_CUSTOMER_ACCOUNT = Identities0.IDENTITY_CUSTOMER_ACCOUNT;
    public static final Identity<ReferralsRecord, Integer> IDENTITY_REFERRALS = Identities0.IDENTITY_REFERRALS;
    public static final Identity<WithdrawalRequestsRecord, Integer> IDENTITY_WITHDRAWAL_REQUESTS = Identities0.IDENTITY_WITHDRAWAL_REQUESTS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountMasternodeRewardsRecord> KEY_ACCOUNT_MASTERNODE_REWARDS_PRIMARY = UniqueKeys0.KEY_ACCOUNT_MASTERNODE_REWARDS_PRIMARY;
    public static final UniqueKey<CurrentAccountRewardsRecord> KEY_CURRENT_ACCOUNT_REWARDS_PRIMARY = UniqueKeys0.KEY_CURRENT_ACCOUNT_REWARDS_PRIMARY;
    public static final UniqueKey<CustomerAccountRecord> KEY_CUSTOMER_ACCOUNT_PRIMARY = UniqueKeys0.KEY_CUSTOMER_ACCOUNT_PRIMARY;
    public static final UniqueKey<CustomerAccountRecord> KEY_CUSTOMER_ACCOUNT_CUST_ID = UniqueKeys0.KEY_CUSTOMER_ACCOUNT_CUST_ID;
    public static final UniqueKey<CustomerLoginsRecord> KEY_CUSTOMER_LOGINS_PRIMARY = UniqueKeys0.KEY_CUSTOMER_LOGINS_PRIMARY;
    public static final UniqueKey<CustomerMasternodeMappingRecord> KEY_CUSTOMER_MASTERNODE_MAPPING_PRIMARY = UniqueKeys0.KEY_CUSTOMER_MASTERNODE_MAPPING_PRIMARY;
    public static final UniqueKey<MasternodeAllRecord> KEY_MASTERNODE_ALL_PRIMARY = UniqueKeys0.KEY_MASTERNODE_ALL_PRIMARY;
    public static final UniqueKey<MasternodeListRecord> KEY_MASTERNODE_LIST_PRIMARY = UniqueKeys0.KEY_MASTERNODE_LIST_PRIMARY;
    public static final UniqueKey<MasternodePayoutsRecord> KEY_MASTERNODE_PAYOUTS_PRIMARY = UniqueKeys0.KEY_MASTERNODE_PAYOUTS_PRIMARY;
    public static final UniqueKey<MasternodeTransactionsRecord> KEY_MASTERNODE_TRANSACTIONS_PRIMARY = UniqueKeys0.KEY_MASTERNODE_TRANSACTIONS_PRIMARY;
    public static final UniqueKey<PacProposalsRecord> KEY_PAC_PROPOSALS_PRIMARY = UniqueKeys0.KEY_PAC_PROPOSALS_PRIMARY;
    public static final UniqueKey<PacPropVotingRecord> KEY_PAC_PROP_VOTING_PRIMARY = UniqueKeys0.KEY_PAC_PROP_VOTING_PRIMARY;
    public static final UniqueKey<ReferralsRecord> KEY_REFERRALS_PRIMARY = UniqueKeys0.KEY_REFERRALS_PRIMARY;
    public static final UniqueKey<WithdrawalRequestsRecord> KEY_WITHDRAWAL_REQUESTS_PRIMARY = UniqueKeys0.KEY_WITHDRAWAL_REQUESTS_PRIMARY;
    public static final UniqueKey<WithdrawalRequestsHistoryRecord> KEY_WITHDRAWAL_REQUESTS_HISTORY_PRIMARY = UniqueKeys0.KEY_WITHDRAWAL_REQUESTS_HISTORY_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CustomerAccountRecord, Integer> IDENTITY_CUSTOMER_ACCOUNT = Internal.createIdentity(CustomerAccount.CUSTOMER_ACCOUNT, CustomerAccount.CUSTOMER_ACCOUNT.UUID);
        public static Identity<ReferralsRecord, Integer> IDENTITY_REFERRALS = Internal.createIdentity(Referrals.REFERRALS, Referrals.REFERRALS.ID);
        public static Identity<WithdrawalRequestsRecord, Integer> IDENTITY_WITHDRAWAL_REQUESTS = Internal.createIdentity(WithdrawalRequests.WITHDRAWAL_REQUESTS, WithdrawalRequests.WITHDRAWAL_REQUESTS.REQUEST_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountMasternodeRewardsRecord> KEY_ACCOUNT_MASTERNODE_REWARDS_PRIMARY = Internal.createUniqueKey(AccountMasternodeRewards.ACCOUNT_MASTERNODE_REWARDS, "KEY_account_masternode_rewards_PRIMARY", AccountMasternodeRewards.ACCOUNT_MASTERNODE_REWARDS.ACCOUNT_ID, AccountMasternodeRewards.ACCOUNT_MASTERNODE_REWARDS.MN_ID);
        public static final UniqueKey<CurrentAccountRewardsRecord> KEY_CURRENT_ACCOUNT_REWARDS_PRIMARY = Internal.createUniqueKey(CurrentAccountRewards.CURRENT_ACCOUNT_REWARDS, "KEY_current_account_rewards_PRIMARY", CurrentAccountRewards.CURRENT_ACCOUNT_REWARDS.ACCOUNT_ID);
        public static final UniqueKey<CustomerAccountRecord> KEY_CUSTOMER_ACCOUNT_PRIMARY = Internal.createUniqueKey(CustomerAccount.CUSTOMER_ACCOUNT, "KEY_customer_account_PRIMARY", CustomerAccount.CUSTOMER_ACCOUNT.UUID);
        public static final UniqueKey<CustomerAccountRecord> KEY_CUSTOMER_ACCOUNT_CUST_ID = Internal.createUniqueKey(CustomerAccount.CUSTOMER_ACCOUNT, "KEY_customer_account_cust_id", CustomerAccount.CUSTOMER_ACCOUNT.ACCOUNT_ID);
        public static final UniqueKey<CustomerLoginsRecord> KEY_CUSTOMER_LOGINS_PRIMARY = Internal.createUniqueKey(CustomerLogins.CUSTOMER_LOGINS, "KEY_customer_logins_PRIMARY", CustomerLogins.CUSTOMER_LOGINS.ACCOUNT_ID);
        public static final UniqueKey<CustomerMasternodeMappingRecord> KEY_CUSTOMER_MASTERNODE_MAPPING_PRIMARY = Internal.createUniqueKey(CustomerMasternodeMapping.CUSTOMER_MASTERNODE_MAPPING, "KEY_customer_masternode_mapping_PRIMARY", CustomerMasternodeMapping.CUSTOMER_MASTERNODE_MAPPING.ACCOUNT_ID, CustomerMasternodeMapping.CUSTOMER_MASTERNODE_MAPPING.MN_ID);
        public static final UniqueKey<MasternodeAllRecord> KEY_MASTERNODE_ALL_PRIMARY = Internal.createUniqueKey(MasternodeAll.MASTERNODE_ALL, "KEY_masternode_all_PRIMARY", MasternodeAll.MASTERNODE_ALL.COL_TXID);
        public static final UniqueKey<MasternodeListRecord> KEY_MASTERNODE_LIST_PRIMARY = Internal.createUniqueKey(MasternodeList.MASTERNODE_LIST, "KEY_masternode_list_PRIMARY", MasternodeList.MASTERNODE_LIST.MN_ID);
        public static final UniqueKey<MasternodePayoutsRecord> KEY_MASTERNODE_PAYOUTS_PRIMARY = Internal.createUniqueKey(MasternodePayouts.MASTERNODE_PAYOUTS, "KEY_masternode_payouts_PRIMARY", MasternodePayouts.MASTERNODE_PAYOUTS.MN_ID, MasternodePayouts.MASTERNODE_PAYOUTS.PAYOUT_DATE);
        public static final UniqueKey<MasternodeTransactionsRecord> KEY_MASTERNODE_TRANSACTIONS_PRIMARY = Internal.createUniqueKey(MasternodeTransactions.MASTERNODE_TRANSACTIONS, "KEY_masternode_transactions_PRIMARY", MasternodeTransactions.MASTERNODE_TRANSACTIONS.MN_ID, MasternodeTransactions.MASTERNODE_TRANSACTIONS.PAYOUT_ADDRESS, MasternodeTransactions.MASTERNODE_TRANSACTIONS.TRANSACTION_ID);
        public static final UniqueKey<PacProposalsRecord> KEY_PAC_PROPOSALS_PRIMARY = Internal.createUniqueKey(PacProposals.PAC_PROPOSALS, "KEY_pac_proposals_PRIMARY", PacProposals.PAC_PROPOSALS.HASH);
        public static final UniqueKey<PacPropVotingRecord> KEY_PAC_PROP_VOTING_PRIMARY = Internal.createUniqueKey(PacPropVoting.PAC_PROP_VOTING, "KEY_pac_prop_voting_PRIMARY", PacPropVoting.PAC_PROP_VOTING.ACCOUNT_ID, PacPropVoting.PAC_PROP_VOTING.HASH);
        public static final UniqueKey<ReferralsRecord> KEY_REFERRALS_PRIMARY = Internal.createUniqueKey(Referrals.REFERRALS, "KEY_referrals_PRIMARY", Referrals.REFERRALS.ID);
        public static final UniqueKey<WithdrawalRequestsRecord> KEY_WITHDRAWAL_REQUESTS_PRIMARY = Internal.createUniqueKey(WithdrawalRequests.WITHDRAWAL_REQUESTS, "KEY_withdrawal_requests_PRIMARY", WithdrawalRequests.WITHDRAWAL_REQUESTS.REQUEST_ID);
        public static final UniqueKey<WithdrawalRequestsHistoryRecord> KEY_WITHDRAWAL_REQUESTS_HISTORY_PRIMARY = Internal.createUniqueKey(WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY, "KEY_withdrawal_requests_history_PRIMARY", WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY.REQUEST_ID);
    }
}
