/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model;


import com.github.jmart1.example.repo.website.model.tables.*;
import net.pacnode.cronservices.repo.website.model.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Pacnode extends SchemaImpl {

    /**
     * The reference instance of <code>pacnode</code>
     */
    public static final Pacnode PACNODE = new Pacnode();
    private static final long serialVersionUID = -1803962772;
    /**
     * The table <code>pacnode.account_masternode_rewards</code>.
     */
    public final AccountMasternodeRewards ACCOUNT_MASTERNODE_REWARDS = AccountMasternodeRewards.ACCOUNT_MASTERNODE_REWARDS;

    /**
     * The table <code>pacnode.admin_users</code>.
     */
    public final AdminUsers ADMIN_USERS = AdminUsers.ADMIN_USERS;

    /**
     * The table <code>pacnode.contact_pacnode</code>.
     */
    public final ContactPacnode CONTACT_PACNODE = ContactPacnode.CONTACT_PACNODE;

    /**
     * The table <code>pacnode.current_account_rewards</code>.
     */
    public final CurrentAccountRewards CURRENT_ACCOUNT_REWARDS = CurrentAccountRewards.CURRENT_ACCOUNT_REWARDS;

    /**
     * The table <code>pacnode.customer_account</code>.
     */
    public final CustomerAccount CUSTOMER_ACCOUNT = CustomerAccount.CUSTOMER_ACCOUNT;

    /**
     * The table <code>pacnode.customer_logins</code>.
     */
    public final CustomerLogins CUSTOMER_LOGINS = CustomerLogins.CUSTOMER_LOGINS;

    /**
     * The table <code>pacnode.customer_masternode_mapping</code>.
     */
    public final CustomerMasternodeMapping CUSTOMER_MASTERNODE_MAPPING = CustomerMasternodeMapping.CUSTOMER_MASTERNODE_MAPPING;

    /**
     * The table <code>pacnode.customer_payouts</code>.
     */
    public final CustomerPayouts CUSTOMER_PAYOUTS = CustomerPayouts.CUSTOMER_PAYOUTS;

    /**
     * The table <code>pacnode.masternode_all</code>.
     */
    public final MasternodeAll MASTERNODE_ALL = MasternodeAll.MASTERNODE_ALL;

    /**
     * The table <code>pacnode.masternode_customers</code>.
     */
    public final MasternodeCustomers MASTERNODE_CUSTOMERS = MasternodeCustomers.MASTERNODE_CUSTOMERS;

    /**
     * The table <code>pacnode.masternode_list</code>.
     */
    public final MasternodeList MASTERNODE_LIST = MasternodeList.MASTERNODE_LIST;

    /**
     * The table <code>pacnode.masternode_payouts</code>.
     */
    public final MasternodePayouts MASTERNODE_PAYOUTS = MasternodePayouts.MASTERNODE_PAYOUTS;

    /**
     * The table <code>pacnode.masternode_transactions</code>.
     */
    public final MasternodeTransactions MASTERNODE_TRANSACTIONS = MasternodeTransactions.MASTERNODE_TRANSACTIONS;

    /**
     * The table <code>pacnode.pacnode_payouts</code>.
     */
    public final PacnodePayouts PACNODE_PAYOUTS = PacnodePayouts.PACNODE_PAYOUTS;

    /**
     * The table <code>pacnode.pac_proposals</code>.
     */
    public final PacProposals PAC_PROPOSALS = PacProposals.PAC_PROPOSALS;

    /**
     * The table <code>pacnode.pac_prop_voting</code>.
     */
    public final PacPropVoting PAC_PROP_VOTING = PacPropVoting.PAC_PROP_VOTING;

    /**
     * The table <code>pacnode.pac_prop_voting_history</code>.
     */
    public final PacPropVotingHistory PAC_PROP_VOTING_HISTORY = PacPropVotingHistory.PAC_PROP_VOTING_HISTORY;

    /**
     * VIEW
     */
    public final PropInfoVotes PROP_INFO_VOTES = PropInfoVotes.PROP_INFO_VOTES;

    /**
     * The table <code>pacnode.referrals</code>.
     */
    public final Referrals REFERRALS = Referrals.REFERRALS;

    /**
     * VIEW
     */
    public final VPayoutHistory V_PAYOUT_HISTORY = VPayoutHistory.V_PAYOUT_HISTORY;

    /**
     * The table <code>pacnode.withdrawal_requests</code>.
     */
    public final WithdrawalRequests WITHDRAWAL_REQUESTS = WithdrawalRequests.WITHDRAWAL_REQUESTS;

    /**
     * The table <code>pacnode.withdrawal_requests_history</code>.
     */
    public final WithdrawalRequestsHistory WITHDRAWAL_REQUESTS_HISTORY = WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY;

    /**
     * No further instances allowed
     */
    private Pacnode() {
        super("pacnode", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                AccountMasternodeRewards.ACCOUNT_MASTERNODE_REWARDS,
                AdminUsers.ADMIN_USERS,
                ContactPacnode.CONTACT_PACNODE,
                CurrentAccountRewards.CURRENT_ACCOUNT_REWARDS,
                CustomerAccount.CUSTOMER_ACCOUNT,
                CustomerLogins.CUSTOMER_LOGINS,
                CustomerMasternodeMapping.CUSTOMER_MASTERNODE_MAPPING,
                CustomerPayouts.CUSTOMER_PAYOUTS,
                MasternodeAll.MASTERNODE_ALL,
                MasternodeCustomers.MASTERNODE_CUSTOMERS,
                MasternodeList.MASTERNODE_LIST,
                MasternodePayouts.MASTERNODE_PAYOUTS,
                MasternodeTransactions.MASTERNODE_TRANSACTIONS,
                PacnodePayouts.PACNODE_PAYOUTS,
                PacProposals.PAC_PROPOSALS,
                PacPropVoting.PAC_PROP_VOTING,
                PacPropVotingHistory.PAC_PROP_VOTING_HISTORY,
                PropInfoVotes.PROP_INFO_VOTES,
                Referrals.REFERRALS,
                VPayoutHistory.V_PAYOUT_HISTORY,
                WithdrawalRequests.WITHDRAWAL_REQUESTS,
                WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY);
    }
}
