/*
 * This file is generated by jOOQ.
 */
package com.github.jmart1.example.repo.website.model;


import com.github.jmart1.example.repo.website.model.tables.*;
import net.pacnode.cronservices.repo.website.model.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in pacnode
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>pacnode.account_masternode_rewards</code>.
     */
    public static final AccountMasternodeRewards ACCOUNT_MASTERNODE_REWARDS = AccountMasternodeRewards.ACCOUNT_MASTERNODE_REWARDS;

    /**
     * The table <code>pacnode.admin_users</code>.
     */
    public static final AdminUsers ADMIN_USERS = AdminUsers.ADMIN_USERS;

    /**
     * The table <code>pacnode.contact_pacnode</code>.
     */
    public static final ContactPacnode CONTACT_PACNODE = ContactPacnode.CONTACT_PACNODE;

    /**
     * The table <code>pacnode.current_account_rewards</code>.
     */
    public static final CurrentAccountRewards CURRENT_ACCOUNT_REWARDS = CurrentAccountRewards.CURRENT_ACCOUNT_REWARDS;

    /**
     * The table <code>pacnode.customer_account</code>.
     */
    public static final CustomerAccount CUSTOMER_ACCOUNT = CustomerAccount.CUSTOMER_ACCOUNT;

    /**
     * The table <code>pacnode.customer_logins</code>.
     */
    public static final CustomerLogins CUSTOMER_LOGINS = CustomerLogins.CUSTOMER_LOGINS;

    /**
     * The table <code>pacnode.customer_masternode_mapping</code>.
     */
    public static final CustomerMasternodeMapping CUSTOMER_MASTERNODE_MAPPING = CustomerMasternodeMapping.CUSTOMER_MASTERNODE_MAPPING;

    /**
     * The table <code>pacnode.customer_payouts</code>.
     */
    public static final CustomerPayouts CUSTOMER_PAYOUTS = CustomerPayouts.CUSTOMER_PAYOUTS;

    /**
     * The table <code>pacnode.masternode_all</code>.
     */
    public static final MasternodeAll MASTERNODE_ALL = MasternodeAll.MASTERNODE_ALL;

    /**
     * The table <code>pacnode.masternode_customers</code>.
     */
    public static final MasternodeCustomers MASTERNODE_CUSTOMERS = MasternodeCustomers.MASTERNODE_CUSTOMERS;

    /**
     * The table <code>pacnode.masternode_list</code>.
     */
    public static final MasternodeList MASTERNODE_LIST = MasternodeList.MASTERNODE_LIST;

    /**
     * The table <code>pacnode.masternode_payouts</code>.
     */
    public static final MasternodePayouts MASTERNODE_PAYOUTS = MasternodePayouts.MASTERNODE_PAYOUTS;

    /**
     * The table <code>pacnode.masternode_transactions</code>.
     */
    public static final MasternodeTransactions MASTERNODE_TRANSACTIONS = MasternodeTransactions.MASTERNODE_TRANSACTIONS;

    /**
     * The table <code>pacnode.pacnode_payouts</code>.
     */
    public static final PacnodePayouts PACNODE_PAYOUTS = PacnodePayouts.PACNODE_PAYOUTS;

    /**
     * The table <code>pacnode.pac_proposals</code>.
     */
    public static final PacProposals PAC_PROPOSALS = PacProposals.PAC_PROPOSALS;

    /**
     * The table <code>pacnode.pac_prop_voting</code>.
     */
    public static final PacPropVoting PAC_PROP_VOTING = PacPropVoting.PAC_PROP_VOTING;

    /**
     * The table <code>pacnode.pac_prop_voting_history</code>.
     */
    public static final PacPropVotingHistory PAC_PROP_VOTING_HISTORY = PacPropVotingHistory.PAC_PROP_VOTING_HISTORY;

    /**
     * VIEW
     */
    public static final PropInfoVotes PROP_INFO_VOTES = PropInfoVotes.PROP_INFO_VOTES;

    /**
     * The table <code>pacnode.referrals</code>.
     */
    public static final Referrals REFERRALS = Referrals.REFERRALS;

    /**
     * VIEW
     */
    public static final VPayoutHistory V_PAYOUT_HISTORY = VPayoutHistory.V_PAYOUT_HISTORY;

    /**
     * The table <code>pacnode.withdrawal_requests</code>.
     */
    public static final WithdrawalRequests WITHDRAWAL_REQUESTS = WithdrawalRequests.WITHDRAWAL_REQUESTS;

    /**
     * The table <code>pacnode.withdrawal_requests_history</code>.
     */
    public static final WithdrawalRequestsHistory WITHDRAWAL_REQUESTS_HISTORY = WithdrawalRequestsHistory.WITHDRAWAL_REQUESTS_HISTORY;
}
